'use client';

import {useEffect,useMemo,useState} from 'react';
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Download,Filter,RefreshCw} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,EmptyState,PageHeader,StatusPill} from '@/components/ui/primitives';

const datasets:any={
 sales:{label:'Monthly sales',view:'v_monthly_sales',columns:['period_month','sales'],titleAr:'المبيعات الشهرية'},
 pipeline:{label:'Pipeline by stage',view:'v_pipeline',columns:['stage','quote_count','total_value'],titleAr:'خط المبيعات حسب المرحلة'},
 health:{label:'Customer health',view:'v_customer_health',columns:['name','last_purchase','days_since_purchase','sales_12m','health_status'],titleAr:'صحة العملاء'},
 regions:{label:'Region performance',view:'v_region_perf',columns:['region_name','sales','invoices'],titleAr:'أداء المناطق'},
 products:{label:'Product performance',view:'v_product_perf',columns:['name','product_group','sales','gp','gp_pct'],titleAr:'أداء المنتجات'},
 reps:{label:'Rep performance',view:'v_rep_month',columns:['rep_id','sales','target','achievement','gp_pct','status'],titleAr:'أداء المندوبين'}
};

export default function ReportBuilder({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId}=useOrg();const [dataset,setDataset]=useState('sales');const [rows,setRows]=useState<any[]>([]);const [query,setQuery]=useState('');const [busy,setBusy]=useState(false);
 const load=async()=>{if(!activeOrgId)return;setBusy(true);const config=datasets[dataset];const {data}=await s.from(config.view).select('*').eq('org_id',activeOrgId).limit(500);setRows(data||[]);setBusy(false)};useEffect(()=>{load()},[activeOrgId,dataset,s]);
 const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));const config=datasets[dataset];
 const exportCsv=()=>{if(!filtered.length)return;const header=config.columns.join(',');const body=filtered.map(r=>config.columns.map((c:string)=>'"'+String(r[c]??'').replaceAll('"','""')+'"').join(',')).join('\n');const blob=new Blob([header+'\n'+body],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='salesos-report-'+dataset+'.csv';a.click();URL.revokeObjectURL(a.href)};
 const chartData=dataset==='sales'?filtered.slice(-18).map(r=>({name:String(r.period_month).slice(0,7),value:Number(r.sales||0)})):dataset==='pipeline'?filtered.map(r=>({name:r.stage,value:Number(r.total_value||0)})):dataset==='regions'?filtered.map(r=>({name:r.region_name||'—',value:Number(r.sales||0)})):dataset==='products'?filtered.slice(0,15).map(r=>({name:r.name||'—',value:Number(r.sales||0)})):dataset==='reps'?filtered.map(r=>({name:String(r.rep_id).slice(0,8),value:Number(r.achievement||0)*100})):filtered.slice(0,15).map(r=>({name:r.name||'—',value:Number(r.sales_12m||0)}));
 return <section className="space-y-6 p-4 md:p-7"><PageHeader eyebrow={ar?'التحليلات':'Analytics'} title={ar?'منشئ التقارير':'Report builder'} description={ar?'اختر مجموعة بيانات آمنة، ابحث، راجع الرسم والجدول، ثم صدّر CSV.':'Choose a safe dataset, filter it, preview a chart and table, then export CSV.'} actions={<div className="flex gap-2"><button onClick={load} className="rounded-xl border px-3 py-2.5 text-sm"><RefreshCw className="me-2 inline size-4"/>{ar?'تحديث':'Refresh'}</button><button onClick={exportCsv} className="rounded-xl bg-neutral-950 px-3 py-2.5 text-sm text-white dark:bg-white dark:text-neutral-950"><Download className="me-2 inline size-4"/>{ar?'تصدير CSV':'Export CSV'}</button></div>}/><div className="grid gap-3 lg:grid-cols-[280px_1fr]"><Card className="p-4"><div className="flex items-center gap-2 text-sm font-medium"><Filter className="size-4"/>{ar?'مجموعة البيانات':'Dataset'}</div><div className="mt-3 space-y-2">{Object.entries(datasets).map(([key,val]:any)=><button key={key} onClick={()=>setDataset(key)} className={"w-full rounded-xl border px-3 py-2.5 text-start text-sm "+(dataset===key?'bg-neutral-950 text-white dark:bg-white dark:text-neutral-950':'hover:bg-neutral-50 dark:hover:bg-neutral-900')}>{ar?val.titleAr:val.label}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={ar?'فلتر سريع...':'Quick filter...'} className="mt-4 w-full rounded-xl border px-3 py-2.5 text-sm"/></Card><div className="space-y-4"><Card className="p-5"><div className="h-72">{chartData.length&&!busy?<ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value" fill="currentColor" fillOpacity={0.65}/></BarChart></ResponsiveContainer>:<div className="flex h-full items-center justify-center text-sm text-neutral-500">{ar?'لا توجد بيانات.':'No data.'}</div>}</div></Card><Card className="overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">{ar?config.titleAr:config.label}</h2><p className="mt-1 text-xs text-neutral-500">{filtered.length} rows</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-neutral-50 dark:bg-neutral-950"><tr>{config.columns.map((c:string)=><th key={c} className="px-4 py-3 text-start">{c}</th>)}</tr></thead><tbody>{filtered.slice(0,100).map((r:any,i:number)=><tr key={r.id||i} className="border-b last:border-0 dark:border-neutral-800">{config.columns.map((c:string)=><td key={c} className="px-4 py-3">{c.includes('pct')||c==='achievement'?<StatusPill status={Number(r[c]||0).toFixed(1)+'%'} />:typeof r[c]==='number'?Number(r[c]).toLocaleString():String(r[c]??'—')}</td>)}</tr>)}</tbody></table>{filtered.length===0&&<EmptyState title={ar?'لا توجد نتائج':'No results'} description={ar?'غيّر مجموعة البيانات أو الفلتر.':'Change the dataset or filter.'}/>}</div></Card></div></div></section>;
}
