'use client';

import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Check,DatabaseZap,Layers3,ShieldCheck,ArrowRight} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';

export function OnboardingForm({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const router=useRouter();const s=useMemo(()=>createClient(),[]);const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false);
 const submit=async()=>{if(name.trim().length<2){setError(ar?'اكتب اسم المؤسسة.':'Enter an organization name.');return}setBusy(true);setError('');const {data,error}=await s.functions.invoke('create-organization',{body:{name:name.trim()}});if(error){setError(error.message);setBusy(false);return}if(data?.org_id)localStorage.setItem('salesos-org',data.org_id);setDone(true);setTimeout(()=>{router.push('/'+locale);router.refresh()},350)};
 return <main className="min-h-screen bg-neutral-50 p-4 dark:bg-neutral-950 md:p-8"><div className="mx-auto grid min-h-[calc(100vh-2rem)] max-w-6xl overflow-hidden rounded-3xl border bg-white shadow-sm dark:border-neutral-800 dark:bg-neutral-900 lg:grid-cols-[.85fr_1.15fr]"><section className="bg-neutral-950 p-8 text-white lg:p-10"><div className="text-sm font-semibold">SalesOS</div><h1 className="mt-14 text-4xl font-semibold tracking-tight">{ar?'نجهز لك مساحة العمل خلال دقائق.':'Your workspace is ready in minutes.'}</h1><p className="mt-5 text-sm leading-7 text-white/60">{ar?'سيتم تجهيز القوالب الافتراضية للأهداف وKPI والعمولات والتنبيهات والمراحل.':'We provision defaults for targets, KPI, commissions, alerts, and pipeline stages.'}</p><div className="mt-10 space-y-3">{[[ShieldCheck,ar?'فصل البيانات حسب المؤسسة':'Organization-level isolation'],[Layers3,ar?'قوالب جاهزة قابلة للتعديل':'Editable templates'],[DatabaseZap,ar?'بيانات تجريبية اختيارية':'Optional demo data']].map(([Icon,label]: any)=><div key={String(label)} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-3 text-sm"><Icon className="size-4 text-white/70"/>{label}</div>)}</div></section><section className="flex items-center p-8 lg:p-14"><div className="w-full max-w-xl"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">{ar?'الخطوة 1 من 1':'Step 1 of 1'}</span><span className="text-xs text-neutral-400">SalesOS</span></div><div className="mt-6 h-2 rounded-full bg-neutral-100 dark:bg-neutral-800"><div className="h-2 w-full rounded-full bg-neutral-950 dark:bg-white"/></div><h2 className="mt-10 text-3xl font-semibold">{ar?'اسم المؤسسة':'Organization name'}</h2><p className="mt-2 text-sm leading-6 text-neutral-500">{ar?'اكتب اسم شركتك أو مساحة العمل. يمكنك تغيير الإعدادات لاحقاً.':'Enter your company or workspace name. You can change settings later.'}</p><label className="mt-7 block text-sm"><span className="mb-2 block font-medium">{ar?'الاسم':'Name'}</span><input autoFocus value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!busy)submit()}} placeholder={ar?'مثال: شركة المبيعات المتحدة':'Example: United Sales Co.'} className="w-full rounded-2xl border px-4 py-4 text-lg outline-none focus:ring-2 dark:border-neutral-700 dark:bg-neutral-950"/></label>{error&&<div className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button onClick={submit} disabled={busy||done} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-neutral-950 px-4 py-4 text-sm font-medium text-white disabled:opacity-50 dark:bg-white dark:text-neutral-950">{done?<><Check className="size-4"/>{ar?'تم التجهيز':'Workspace ready'}</>:(busy?(ar?'جارٍ تجهيز المساحة...':'Provisioning...'):(ar?'متابعة إلى المنصة':'Continue to workspace'))}<ArrowRight className="size-4"/></button></div></section></div></main>;
}
