'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {Activity,Bell,Boxes,CalendarDays,BriefcaseBusiness,Building2,ChartNoAxesCombined,CheckSquare,Coins,FileBarChart,Gauge,Home,Kanban,Landmark,Layers3,Map,Package,Plug,Receipt,Settings,Target,Upload,UserCheck,Users,WalletCards,Sparkles,ChevronLeft,ChevronRight,UserRoundCog} from 'lucide-react';
import {navGroups} from '@/lib/navigation';
import {QuickAdd} from '@/components/quick-add/quick-add';
const icons:Record<string,any>={home:Home,receipt:Receipt,building:Building2,users:Users,target:Target,briefcase:BriefcaseBusiness,kanban:Kanban,activity:Activity,check:CheckSquare,wallet:WalletCards,gauge:Gauge,package:Package,map:Map,layers:Layers3,'user-check':UserCheck,sparkles:Sparkles,chart:ChartNoAxesCombined,coins:Coins,landmark:Landmark,report:FileBarChart,bell:Bell,bot:Sparkles,calendar:CalendarDays,upload:Upload,plug:Plug,settings:Settings,'user-round-cog':UserRoundCog};
export function AppShell({children}:{children:React.ReactNode}){const path=usePathname();const locale=(path.split('/')[1]||'ar') as 'ar'|'en';const ar=locale==='ar';const [collapsed,setCollapsed]=useState(false);return <div className="min-h-screen bg-neutral-50 text-neutral-950 dark:bg-neutral-950 dark:text-neutral-50"><aside className={(collapsed?'w-[72px]':'w-[260px]')+" fixed inset-y-0 start-0 z-50 hidden flex-col border-e border-neutral-200 bg-white p-3 transition-all dark:border-neutral-800 dark:bg-neutral-950 lg:flex"}><div className="flex items-center justify-between gap-2 px-2 py-2"><Link href={'/'+locale} className="flex min-w-0 items-center gap-2.5"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-neutral-950 text-white dark:bg-white dark:text-neutral-950"><Boxes className="size-5"/></span>{!collapsed&&<span className="font-semibold tracking-tight">SalesOS</span>}</Link><button onClick={()=>setCollapsed(v=>!v)} className="rounded-lg p-2 text-neutral-500 hover:bg-neutral-100 dark:hover:bg-neutral-900" aria-label="toggle sidebar">{collapsed?<ChevronRight className="size-4"/>:<ChevronLeft className="size-4" />}</button></div><div className="mt-5 flex-1 space-y-5 overflow-y-auto">{navGroups.map(group=><div key={group.label}><p className={(collapsed?'sr-only ':'')+"mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-neutral-400"}>{group.label}</p><nav className="space-y-1">{group.items.map(item=>{const Icon=icons[item.icon]||Boxes;const href='/'+locale+item.href;const active=path===href||path.startsWith(href+'/');return <Link key={item.id} href={href} title={collapsed?(ar?item.ar:item.en):undefined} className={"group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm "+(active?"bg-neutral-950 text-white dark:bg-white dark:text-neutral-950":"text-neutral-600 hover:bg-neutral-100 dark:text-neutral-300 dark:hover:bg-neutral-900")+" "+(collapsed?"justify-center":"")}><Icon className="size-4 shrink-0"/>{!collapsed&&<span className="truncate">{ar?item.ar:item.en}</span>}{!collapsed&&active&&<span className="ms-auto size-1.5 rounded-full bg-current opacity-60"/>}</Link>})}</nav></div>)}</div>{!collapsed&&<div className="border-t border-neutral-200 pt-3 dark:border-neutral-800"><div className="rounded-xl bg-neutral-50 p-3 text-xs dark:bg-neutral-900"><div className="font-medium">{ar?'مساحة عملك':'Your workspace'}</div><p className="mt-1 text-neutral-500">{ar?'كل المبيعات والأهداف والعمليات في مصدر واحد.':'One source for sales, targets, and operations.'}</p></div></div>}</aside><div className={(collapsed?'lg:ms-[72px]':'lg:ms-[260px]')+" min-h-screen"}><main>{children}</main></div><QuickAdd locale={locale}/></div>}
