export type HelpArticle={id:string;category:string;titleAr:string;titleEn:string;bodyAr:string;bodyEn:string;stepsAr:string[];stepsEn:string[];keywords:string[]};
export const HELP_ARTICLES:HelpArticle[]=[
{id:'start',category:'getting-started',titleAr:'كيف أبدأ؟',titleEn:'How do I start?',bodyAr:'أضف العملاء والمنتجات، ثم حدّد الأهداف وسجّل أول بيع. بعد ذلك استخدم اليوم والتنبيهات لمعرفة ما يحتاج إجراء.',bodyEn:'Add customers and products, set targets, and record the first sale. Then use Today and Alerts to know what needs action.',stepsAr:['أضف العملاء والمنتجات.','حدّد الأهداف.','سجّل البيع والتحصيل.','راجع اليوم والتنبيهات.'],stepsEn:['Add customers and products.','Set targets.','Record sales and collections.','Review Today and Alerts.'],keywords:['start','begin','setup','ابدأ']},
{id:'sales',category:'sales',titleAr:'كيف أسجل بيعاً؟',titleEn:'How do I record a sale?',bodyAr:'استخدم بيع سريع من زر الإضافة. اختر العميل والمنتجات وطريقة الدفع، ثم احفظ.',bodyEn:'Use Quick sale from Quick Add. Choose the customer, products, and payment method, then save.',stepsAr:['فتح بيع سريع.','اختيار العميل.','إضافة المنتجات والكميات.','اختيار الدفع والحفظ.'],stepsEn:['Open Quick sale.','Choose the customer.','Add products and quantities.','Choose payment and save.'],keywords:['sale','invoice','بيع','فاتورة']},
{id:'staff',category:'people',titleAr:'كيف أضيف موظفاً؟',titleEn:'How do I add staff?',bodyAr:'من الموظفون أضف ملف الموظف، المسمى، الاتصال، الراتب والهدف. يمكن إنشاء السجل أولاً ثم دعوة الموظف للدخول لاحقاً.',bodyEn:'Use Staff to add the employee profile, role, contact, salary, and target. Create the record first and invite login later.',stepsAr:['افتح الموظفون.','أضف البيانات.','حدد الراتب والهدف.','أرسل دعوة الدخول عند توفر إعداد الدعوات.'],stepsEn:['Open Staff.','Add the details.','Set salary and target.','Send a login invitation when invitation secrets are configured.'],keywords:['staff','employee','rep','موظف','مندوب']},
{id:'payroll',category:'money',titleAr:'كيف تُحسب الرواتب والعمولات؟',titleEn:'How are payroll and commissions calculated?',bodyAr:'التشغيل الذكي يجمع المبيعات والهدف والهامش والتحصيل وأحدث KPI شهري ويطبق خطة العمولة، ثم يسمح بالمراجعة والاعتماد والقفل.',bodyEn:'Smart payroll combines sales, target, margin, collections, and the latest monthly KPI, applies the commission plan, then allows review, approval, and locking.',stepsAr:['ضبط الراتب وخطة العمولة.','ضبط أهداف المندوبين.','تعبئة KPI للشهر.','تشغيل الرواتب ومراجعتها واعتمادها.'],stepsEn:['Set salary and commission plan.','Set rep targets.','Populate monthly KPI.','Run, review, and approve payroll.'],keywords:['payroll','salary','commission','kpi','راتب','عمولة']},
{id:'ai',category:'ai',titleAr:'كيف يعمل المساعد الذكي؟',titleEn:'How does AI work?',bodyAr:'المساعد يستخرج أرقام SalesOS ويجيب عن المبيعات والـPipeline والتحصيل والعملاء والموظفين وطريقة استخدام الأدوات. عند وجود AI_API_KEY وAI_MODEL على الخادم يستخدم نموذجاً لغوياً حقيقياً، وإلا يعمل الوضع المحلي المجاني.',bodyEn:'The copilot uses SalesOS data for sales, pipeline, collections, customers, staff, and how-to questions. With server-side AI_API_KEY and AI_MODEL it uses a real LLM; otherwise it uses the free local mode.',stepsAr:['اسأل سؤالاً مباشراً.','جرّب الأسئلة الجاهزة.','اطلب الإجراء التالي.'],stepsEn:['Ask a direct question.','Use a suggested prompt.','Ask for the next action.'],keywords:['ai','assistant','copilot','مساعد']},
{id:'exports',category:'platform',titleAr:'كيف أُصدر البيانات؟',titleEn:'How do I export data?',bodyAr:'مركز التصدير يوفر Excel متعدد الأوراق وJSON احتياطي وCSV حسب الجدول وصفحة طباعة لحفظ PDF من المتصفح.',bodyEn:'Export Center provides multi-sheet Excel, JSON backup, table CSV, and a print view for saving as PDF.',stepsAr:['افتح مركز التصدير.','اختر Excel أو JSON أو CSV.','استخدم طباعة / حفظ PDF.'],stepsEn:['Open Export Center.','Choose Excel, JSON, or CSV.','Use Print / Save PDF.'],keywords:['export','excel','csv','pdf','json','تصدير']},
{id:'extensions',category:'platform',titleAr:'كيف تعمل الامتدادات؟',titleEn:'How do extensions work?',bodyAr:'الامتدادات تستخدم manifest منظم للثيمات والاختصارات وبطاقات المؤشرات والأتمتة. الواجهة لا تسمح بتشغيل JavaScript عشوائي داخل حسابك.',bodyEn:'Extensions use controlled manifests for themes, shortcuts, metrics, and automation. The UI does not allow arbitrary JavaScript execution.',stepsAr:['افتح الامتدادات.','استخدم منشئ الامتدادات.','احفظ manifest.','فعّل الامتداد.'],stepsEn:['Open Extensions.','Use Extension Builder.','Save the manifest.','Enable the extension.'],keywords:['extension','plugin','theme','manifest','امتداد']}
];