'use client';

import {useEffect,useMemo,useState} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {Building2,Command,FileText,Plus,Receipt,Search,Sparkles,UserRoundCheck,Users} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {navGroups} from '@/lib/navigation';
import {useOrg} from '@/lib/org/context';

const typeIcon:any={account:Building2,contact:Users,lead:UserRoundCheck,deal:FileText,invoice:Receipt};

export function CommandPalette(){
 const path=usePathname();const router=useRouter();const locale=(path.split('/')[1]||'ar') as 'ar'|'en';const ar=locale==='ar';const [open,setOpen]=useState(false);const [q,setQ]=useState('');const [results,setResults]=useState<any[]>([]);const [loading,setLoading]=useState(false);const {activeOrgId}=useOrg();const supabase=useMemo(()=>createClient() as any,[]);
 const items=useMemo(()=>navGroups.flatMap(g=>g.items.map(i=>({id:i.id,href:i.href,label:ar?i.ar:i.en}))),[ar]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(v=>!v)}if(e.key==='Escape')setOpen(false)};const custom=()=>setOpen(true);window.addEventListener('keydown',key);window.addEventListener('salesos:command',custom);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('salesos:command',custom)}},[]);
 useEffect(()=>{let alive=true;const run=async()=>{if(!open||q.trim().length<2||!activeOrgId){setResults([]);return}setLoading(true);const term='%'+q.trim()+'%';const [a,c,l,d,i]=await Promise.all([supabase.from('accounts').select('id,name').eq('org_id',activeOrgId).ilike('name',term).limit(5),supabase.from('contacts').select('id,first_name,last_name').eq('org_id',activeOrgId).or('first_name.ilike.'+term+',last_name.ilike.'+term).limit(5),supabase.from('leads').select('id,name,company').eq('org_id',activeOrgId).ilike('name',term).limit(5),supabase.from('deals').select('id,title,value').eq('org_id',activeOrgId).ilike('title',term).limit(5),supabase.from('invoices').select('id,invoice_number,total').eq('org_id',activeOrgId).ilike('invoice_number',term).limit(5)]);if(alive){setResults([...((a.data||[]).map((x:any)=>({...x,type:'account',title:x.name,href:'/accounts/'+x.id}))),...((c.data||[]).map((x:any)=>({...x,type:'contact',title:x.first_name+' '+(x.last_name||''),href:'/contacts'}))),...((l.data||[]).map((x:any)=>({...x,type:'lead',title:x.name,meta:x.company,href:'/leads'}))),...((d.data||[]).map((x:any)=>({...x,type:'deal',title:x.title,meta:Number(x.value||0).toLocaleString()+' EGP',href:'/deals'}))),...((i.data||[]).map((x:any)=>({...x,type:'invoice',title:x.invoice_number,meta:Number(x.total||0).toLocaleString()+' EGP',href:'/sales/'+x.id})))]);setLoading(false)}};const timer=setTimeout(run,220);return()=>{alive=false;clearTimeout(timer)}},[open,q,activeOrgId,supabase]);
 if(!open)return null;
 const filtered=items.filter(i=>i.label.toLowerCase().includes(q.toLowerCase())).slice(0,14);
 const go=(href:string)=>{router.push('/'+locale+href);setOpen(false);setQ('')};
 return <div className="fixed inset-0 z-[70] bg-black/40 p-4 backdrop-blur-sm" onMouseDown={()=>setOpen(false)}><div className="mx-auto mt-[8vh] max-w-2xl overflow-hidden rounded-3xl border bg-white shadow-2xl dark:border-neutral-800 dark:bg-neutral-900" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b px-4"><Search className="size-4 text-neutral-400"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث في العملاء والصفقات والفواتير...':'Search customers, deals, invoices...'} className="h-14 flex-1 bg-transparent outline-none"/>{loading&&<span className="text-[11px] text-neutral-400">…</span>}</div><div className="max-h-[65vh] overflow-y-auto p-2">{q.trim().length>=2&&<div className="mb-2">{results.map(item=>{const Icon=typeIcon[item.type]||Command;return <button key={item.type+item.id} onClick={()=>go(item.href)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-start text-sm hover:bg-neutral-100 dark:hover:bg-neutral-800"><span className="flex size-8 items-center justify-center rounded-lg border"><Icon className="size-4"/></span><span className="min-w-0 flex-1"><span className="block truncate font-medium">{item.title}</span><span className="block truncate text-[11px] text-neutral-500">{item.meta||item.type}</span></span><span className="text-[10px] text-neutral-400">↗</span></button>})}{results.length===0&&!loading&&<div className="p-6 text-center text-sm text-neutral-500">{ar?'لا نتائج.':'No results.'}</div>}</div>}<div className="mb-1 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-neutral-400">{ar?'التنقل':'Navigate'}</div>{filtered.map(item=><button key={item.id} onClick={()=>go(item.href)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-start text-sm hover:bg-neutral-100 dark:hover:bg-neutral-800"><span className="flex size-8 items-center justify-center rounded-lg border"><Command className="size-4"/></span>{item.label}</button>)}{q.length===0&&<div className="grid gap-2 border-t p-2 sm:grid-cols-2"><button onClick={()=>go('/sales/new')} className="rounded-xl border p-3 text-start text-sm"><Plus className="mb-1 size-4"/>{ar?'تسجيل بيع':'Record sale'}</button><button onClick={()=>go('/assistant')} className="rounded-xl border p-3 text-start text-sm"><Sparkles className="mb-1 size-4"/>{ar?'اسأل المساعد':'Ask assistant'}</button></div>}</div></div></div>
}
