'use client';
import {useState} from 'react';
import {Download,FileJson,FileSpreadsheet,FileText,Printer} from 'lucide-react';
import * as XLSX from 'xlsx';
export default function Exports(){
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [table,setTable]=useState('accounts');
 const get=async()=>{setBusy(true);setMessage('');try{const r=await fetch('/api/export');const d=await r.json();if(!r.ok)throw new Error(d.error||'Export failed');return d}catch(e){setMessage(e instanceof Error?e.message:'Export failed');return null}finally{setBusy(false)}};
 const downloadBlob=(data:BlobPart,type:string,name:string)=>{const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
 const json=async()=>{const d=await get();if(d)downloadBlob(JSON.stringify(d,null,2),'application/json','salesos-full-backup.json')};
 const excel=async()=>{const d=await get();if(!d)return;const wb=XLSX.utils.book_new();for(const [name,rows] of Object.entries<any[]>(d.tables||{})){const ws=XLSX.utils.json_to_sheet(rows||[]);XLSX.utils.book_append_sheet(wb,ws,name.slice(0,31).replace(/[\\/?*\\[\\]:]/g,'_'))}XLSX.writeFile(wb,'salesos-full-export.xlsx')};
 const csv=async()=>{const d=await get();if(!d)return;const rows=(d.tables?.[table]||[]) as any[];if(!rows.length){setMessage('No rows in selected table');return}const headers=Object.keys(rows[0]);const out=[headers.join(','),...rows.map(row=>headers.map(h=>'"'+String(row[h]??'').replaceAll('"','""')+'"').join(','))].join('\n');downloadBlob(out,'text/csv;charset=utf-8','salesos-'+table+'.csv')};
 return <section className="space-y-6 p-4 md:p-7"><div><p className="text-xs uppercase tracking-[0.18em] text-neutral-400">SalesOS</p><h1 className="mt-1 text-3xl font-semibold">Export Center</h1><p className="mt-2 max-w-2xl text-sm text-neutral-500">Excel, JSON backup, CSV, and print/PDF from one fast screen.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><button disabled={busy} onClick={excel} className="rounded-2xl border bg-white p-5 text-start dark:border-neutral-800 dark:bg-neutral-900"><FileSpreadsheet className="size-5"/><div className="mt-4 font-semibold">Full Excel</div><p className="mt-1 text-xs text-neutral-500">Every exported table as a separate sheet.</p></button><button disabled={busy} onClick={json} className="rounded-2xl border bg-white p-5 text-start dark:border-neutral-800 dark:bg-neutral-900"><FileJson className="size-5"/><div className="mt-4 font-semibold">JSON backup</div><p className="mt-1 text-xs text-neutral-500">Full backup for restore.</p></button><div className="rounded-2xl border bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><FileText className="size-5"/><div className="mt-4 font-semibold">CSV</div><select value={table} onChange={e=>setTable(e.target.value)} className="mt-3 w-full rounded-xl border bg-transparent px-3 py-2 text-sm"><option>accounts</option><option>contacts</option><option>leads</option><option>deals</option><option>invoices</option><option>payments</option><option>reps</option><option>payroll_lines</option></select><button disabled={busy} onClick={csv} className="mt-3 inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm"><Download className="size-4"/>Download CSV</button></div><a href={location.pathname.split("/").slice(0,2).join("/")+"/exports/print"} target="_blank" rel="noreferrer" className="rounded-2xl border bg-white p-5 text-start dark:border-neutral-800 dark:bg-neutral-900"><Printer className="size-5"/><div className="mt-4 font-semibold">PDF / Print</div><p className="mt-1 text-xs text-neutral-500">Open a print-ready report and Save as PDF.</p></a></div>{message&&<p className="rounded-xl border p-3 text-sm text-neutral-500">{message}</p>}</section>
}