'use client';
import {useEffect,useMemo,useState} from 'react';
import {Medal,TrendingUp,Users} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,EmptyState,PageHeader,StatusPill} from '@/components/ui/primitives';

export default function Performance(){
 const p=typeof window!=='undefined'?window.location.pathname:'/ar/performance';const ar=p.split('/')[1]!=='en';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId}=useOrg();const [rows,setRows]=useState<any[]>([]);
 useEffect(()=>{(async()=>{if(!activeOrgId)return;const {data}=await s.from('v_rep_month').select('*').eq('org_id',activeOrgId).order('achievement',{ascending:false});setRows(data||[])})()},[activeOrgId,s]);
 const avg=rows.length?rows.reduce((n,r)=>n+Number(r.achievement||0),0)/rows.length:0;const top=rows[0];
 return <section className="space-y-6 p-4 md:p-7"><PageHeader eyebrow={ar?'الأداء':'Performance'} title={ar?'أداء المندوبين':'Rep performance'} description={ar?'ترتيب المندوبين مقابل الهدف مع عرض المبيعات والهامش حسب الصلاحية.':'Rep ranking versus target with sales and margin shown according to role.'}/><div className="grid gap-3 md:grid-cols-3"><Card className="p-5"><Medal className="size-5 text-neutral-500"/><p className="mt-4 text-xs text-neutral-400">{ar?'المتصدر':'Top rep'}</p><p className="mt-1 text-2xl font-semibold">{top?(Number(top.achievement||0)*100).toFixed(0)+'%':'—'}</p></Card><Card className="p-5"><TrendingUp className="size-5 text-neutral-500"/><p className="mt-4 text-xs text-neutral-400">{ar?'متوسط الفريق':'Team average'}</p><p className="mt-1 text-2xl font-semibold">{(avg*100).toFixed(0)}%</p></Card><Card className="p-5"><Users className="size-5 text-neutral-500"/><p className="mt-4 text-xs text-neutral-400">{ar?'المندوبون':'Reps'}</p><p className="mt-1 text-2xl font-semibold">{rows.length}</p></Card></div><Card className="overflow-hidden"><div className="border-b p-5 dark:border-neutral-800"><h2 className="font-semibold">{ar?'لوحة الترتيب':'Leaderboard'}</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-neutral-50 dark:border-neutral-800 dark:bg-neutral-950"><tr><th className="px-4 py-3 text-start">#</th><th className="px-4 py-3 text-start">Rep</th><th className="px-4 py-3 text-start">Sales</th><th className="px-4 py-3 text-start">Target</th><th className="px-4 py-3 text-start">Achievement</th><th className="px-4 py-3 text-start">GP%</th><th className="px-4 py-3 text-start">Status</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.rep_id} className="border-b last:border-0 dark:border-neutral-800"><td className="px-4 py-3 font-semibold">{i+1}</td><td className="px-4 py-3 font-mono text-xs">{r.rep_id}</td><td className="px-4 py-3">{Number(r.sales||0).toLocaleString()} EGP</td><td className="px-4 py-3">{Number(r.target||0).toLocaleString()} EGP</td><td className="px-4 py-3 font-semibold">{(Number(r.achievement||0)*100).toFixed(1)}%</td><td className="px-4 py-3">{Number(r.gp_pct||0).toFixed(1)}%</td><td className="px-4 py-3"><StatusPill status={r.status||'ACTION'}/></td></tr>)}</tbody></table>{rows.length===0&&<EmptyState title={ar?'لا توجد بيانات أداء':'No performance data'} description={ar?'حدد الأهداف وأدخل المبيعات لبدء القياس.':'Set targets and record sales to start measuring.'}/>}</div></Card></section>
}
