export type NavGroup={label:string;items:Array<{id:string;href:string;ar:string;en:string;icon:string}>};
export const navGroups:NavGroup[]=[
{label:'workspace',items:[
{id:'home',href:'/',ar:'اليوم',en:'Today',icon:'home'},{id:'sales',href:'/sales',ar:'المبيعات',en:'Sales',icon:'receipt'},{id:'accounts',href:'/accounts',ar:'الحسابات',en:'Customers',icon:'building'},{id:'contacts',href:'/contacts',ar:'جهات الاتصال',en:'Contacts',icon:'users'},{id:'leads',href:'/leads',ar:'العملاء المحتملون',en:'Leads',icon:'target'},{id:'deals',href:'/deals',ar:'الفرص',en:'Deals',icon:'briefcase'},{id:'pipeline',href:'/pipeline',ar:'خط المبيعات',en:'Pipeline',icon:'kanban'}]},
{label:'operations',items:[
{id:'calendar',href:'/calendar',ar:'التقويم',en:'Calendar',icon:'calendar'},{id:'activities',href:'/activities',ar:'الزيارات والمتابعة',en:'Activities',icon:'activity'},{id:'tasks',href:'/tasks',ar:'المهام',en:'Tasks',icon:'check'},{id:'collections',href:'/collections',ar:'التحصيل',en:'Collections',icon:'wallet'},{id:'targets',href:'/targets',ar:'الأهداف',en:'Targets',icon:'gauge'},{id:'products',href:'/products',ar:'المنتجات',en:'Products',icon:'package'},{id:'regions',href:'/regions',ar:'المناطق',en:'Regions',icon:'map'},{id:'teams',href:'/teams',ar:'الفرق',en:'Teams',icon:'layers'}]},
{label:'people & finance',items:[
{id:'staff',href:'/staff',ar:'الموظفون والفريق',en:'Staff & team',icon:'staff'},{id:'reps',href:'/reps',ar:'المندوبون',en:'Reps',icon:'user-check'},{id:'kpi',href:'/kpi',ar:'KPI',en:'KPI',icon:'sparkles'},{id:'performance',href:'/performance',ar:'الأداء',en:'Performance',icon:'chart'},{id:'payroll',href:'/payroll',ar:'الرواتب والعمولات',en:'Payroll',icon:'coins'},{id:'finance',href:'/finance',ar:'المالية',en:'Finance',icon:'landmark'},{id:'hr',href:'/hr',ar:'الموارد البشرية',en:'HR',icon:'user-round-cog'}]},
{label:'insights & platform',items:[
{id:'reports',href:'/reports',ar:'التقارير',en:'Reports',icon:'report'},{id:'alerts',href:'/alerts',ar:'التنبيهات',en:'Alerts',icon:'bell'},{id:'brief',href:'/brief',ar:'موجز اليوم',en:'Daily Brief',icon:'sparkles'},{id:'assistant',href:'/assistant',ar:'المساعد الذكي',en:'AI Copilot',icon:'bot'},{id:'import',href:'/import',ar:'استيراد البيانات',en:'Import',icon:'upload'},{id:'exports',href:'/exports',ar:'مركز التصدير',en:'Export Center',icon:'exports'},{id:'extensions',href:'/extensions',ar:'الامتدادات والتكاملات',en:'Extensions & integrations',icon:'plug'},{id:'themes',href:'/themes',ar:'الثيمات والأنماط',en:'Themes & styles',icon:'themes'},{id:'help',href:'/help',ar:'مركز المساعدة',en:'Help center',icon:'help'},{id:'settings',href:'/settings',ar:'الإعدادات',en:'Settings',icon:'settings'}]}
];