'use client';

import {useMemo,useState} from 'react';
import {Sparkles} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';

export default function AssistantPage(){
 const p=typeof window!=='undefined'?window.location.pathname:'/ar/assistant';const ar=p.split('/')[1]!=='en';const {activeOrgId}=useOrg();const s=useMemo(()=>createClient(),[]);const [q,setQ]=useState('');const [answer,setAnswer]=useState('');
 const ask=async(text:string)=>{if(!activeOrgId)return;const lower=text.toLowerCase();let out='';if(lower.includes('revenue')||lower.includes('إيراد')||lower.includes('مدفوع')){const {data}=await s.from('payments').select('amount').eq('org_id',activeOrgId);out=(ar?'المدفوعات المستلمة: ':'Received payments: ')+(data??[]).reduce((x,r)=>x+Number(r.amount||0),0).toLocaleString()+' EGP';}else if(lower.includes('pipeline')||lower.includes('صفقات')||lower.includes('pipeline')){const {data}=await s.from('deals').select('value,status').eq('org_id',activeOrgId).eq('status','open');out=(ar?'قيمة خط الصفقات المفتوحة: ':'Open pipeline: ')+(data??[]).reduce((x,r)=>x+Number(r.value||0),0).toLocaleString()+' EGP';}else if(lower.includes('lead')||lower.includes('عملاء')){const {count}=await s.from('leads').select('*',{count:'exact',head:true}).eq('org_id',activeOrgId);out=(ar?'عدد العملاء المحتملين: ':'Leads: ')+(count??0);}else if(lower.includes('task')||lower.includes('مهام')){const {count}=await s.from('tasks').select('*',{count:'exact',head:true}).eq('org_id',activeOrgId).neq('status','done');out=(ar?'المهام المفتوحة: ':'Open tasks: ')+(count??0);}else{out=ar?'جرّب: الإيرادات، الصفقات، العملاء المحتملين، أو المهام.':'Try: revenue, pipeline, leads, or tasks.'}setAnswer(out)};
 return <section className="p-4 md:p-8"><div className="max-w-3xl"><div className="flex items-center gap-2"><Sparkles className="size-5"/><h1 className="text-2xl font-semibold">{ar?'المساعد':'Assistant'}</h1></div><p className="mt-1 text-sm text-neutral-500">{ar?'مساعد محلي مجاني يجيب من بيانات مؤسستك.':'Free local assistant using your organization data.'}</p><div className="mt-6 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ask(q)}} placeholder={ar?'اسأل عن الإيرادات أو الصفقات...':'Ask about revenue or pipeline...'} className="flex-1 rounded-xl border bg-white px-3 py-3 dark:border-neutral-800 dark:bg-neutral-900"/><button onClick={()=>ask(q)} className="rounded-xl bg-neutral-950 px-4 py-3 text-white dark:bg-white dark:text-neutral-950">Ask</button></div><div className="mt-4 flex flex-wrap gap-2">{['revenue','pipeline','leads','tasks'].map(x=><button key={x} onClick={()=>ask(x)} className="rounded-full border px-3 py-1.5 text-xs">{x}</button>)}</div>{answer&&<div className="mt-6 rounded-2xl border bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="text-sm text-neutral-500">{ar?'النتيجة':'Result'}</div><p className="mt-2 text-xl font-semibold">{answer}</p></div>}</div></section>;
}
