'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {FileText,Paperclip,Send,Sparkles,X,CheckCircle2} from 'lucide-react';
import {SalesOSMascot,MascotMood} from '@/components/assistant/mascot';

function speak(text:string,locale:string){if(typeof window==='undefined'||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=locale==='ar'?'ar-EG':'en-US';u.rate=1.03;u.pitch=1.08;window.speechSynthesis.speak(u)}
function playFx(enabled:boolean,kind:MascotMood){if(!enabled||typeof window==='undefined')return;try{const Ctx=(window.AudioContext||((window as any).webkitAudioContext));const ctx=new Ctx();const o=ctx.createOscillator();const g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=kind==='celebrate'?880:kind==='eating'?180:kind==='surprised'?640:kind==='thinking'?320:kind==='confused'?120:480;g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.06,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.18);o.start();o.stop(ctx.currentTime+.2)}catch{}}

export function AICopilotDock({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const [open,setOpen]=useState(false);const [q,setQ]=useState('');const [busy,setBusy]=useState(false);const [mood,setMood]=useState<MascotMood>('idle');const [sound,setSound]=useState(true);const [answer,setAnswer]=useState<any>(null);const [files,setFiles]=useState<File[]>([]);const [applied,setApplied]=useState('');const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const s=localStorage.getItem('salesos-ai-sound');if(s!==null)setSound(s==='1');const fn=()=>setOpen(true);window.addEventListener('salesos:assistant',fn);return()=>window.removeEventListener('salesos:assistant',fn)},[]);
 useEffect(()=>{if(mood==='idle')return;const id=window.setTimeout(()=>setMood('idle'),2200);return()=>window.clearTimeout(id)},[mood]);
 const ask=async()=>{if(!q.trim()&&!files.length)return;setBusy(true);setAnswer(null);setApplied('');const next=files.length?'eating':'thinking';setMood(next);playFx(sound,next);try{const f=new FormData();f.set('question',q);f.set('locale',locale);files.forEach(x=>f.append('files',x));const r=await fetch('/api/assistant',{method:'POST',body:f});const ct=r.headers.get('content-type')||'';const d=ct.includes('application/json')?await r.json():{error:'AI endpoint returned non-JSON data (HTTP '+r.status+')'};if(!r.ok)throw new Error(d.error||'AI request failed');setAnswer(d);const m=(d.mood||'happy') as MascotMood;setMood(m);playFx(sound,m);if(d.text)speak(d.text,locale)}catch(e){setAnswer({text:e instanceof Error?e.message:'AI request failed',links:[]});setMood('confused');playFx(sound,'confused')}finally{setBusy(false)}};
 const apply=async()=>{if(!answer?.action||answer.action.type==='none')return;setBusy(true);try{const r=await fetch('/api/assistant/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:answer.action})});const ct=r.headers.get('content-type')||'';const d=ct.includes('application/json')?await r.json():{error:'Action endpoint returned non-JSON data.'};if(!r.ok)throw new Error(d.error||'Action failed');setApplied(ar?'تم تنفيذ الإجراء.':'Action applied.');setMood('celebrate');playFx(sound,'celebrate')}catch(e){setApplied(e instanceof Error?e.message:'Action failed');setMood('confused')}finally{setBusy(false)}};
 return <><button onClick={()=>setOpen(true)} className="fixed bottom-5 start-5 z-50 hidden items-center gap-2 rounded-full border bg-white px-3 py-2 text-xs shadow-lg dark:border-neutral-800 dark:bg-neutral-900 md:flex"><span className="flex size-6 items-center justify-center rounded-full bg-neutral-950 text-white dark:bg-white dark:text-neutral-950">✦</span>{ar?'اسأل AI':'Ask AI'}</button>
 {open&&<div className="fixed inset-0 z-[90] bg-black/35 p-3 backdrop-blur-sm" onMouseDown={()=>setOpen(false)}><div className="absolute bottom-3 start-3 w-[min(760px,calc(100vw-24px))] overflow-hidden rounded-3xl border bg-white shadow-2xl dark:border-neutral-800 dark:bg-neutral-950" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b px-4 py-3 dark:border-neutral-800"><div className="flex items-center gap-2"><Sparkles className="size-4"/><span className="text-sm font-semibold">SalesOS AI</span><span className="rounded-full border px-2 py-0.5 text-[10px]">{answer?.mode==='real'?'Gemini':'Local'}</span></div><button onClick={()=>setOpen(false)} className="rounded-lg border p-1.5"><X className="size-4"/></button></div>
 <div className="grid gap-4 p-4 md:grid-cols-[150px_1fr]"><div className="flex justify-center"><SalesOSMascot mood={mood} sound={sound} onToggleSound={()=>{setSound(v=>{const n=!v;localStorage.setItem('salesos-ai-sound',n?'1':'0');return n})}} onSpeak={()=>answer?.text&&speak(answer.text,locale)} small/></div>
 <div><div className="flex flex-wrap gap-2">{files.map(f=><span key={f.name+f.size} className="inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[11px]"><FileText className="size-3"/>{f.name}<button onClick={()=>setFiles(v=>v.filter(x=>x!==f))}>×</button></span>)}</div>
 <div className="mt-2 flex gap-2 rounded-2xl border p-2 dark:border-neutral-800"><textarea value={q} onChange={e=>setQ(e.target.value)} rows={3} className="min-h-20 flex-1 resize-none bg-transparent p-2 text-sm outline-none" placeholder={ar?'اكتب سؤالك أو ارفع ملفات، وأنا أقرأها وأحللها.':'Ask anything or attach files for analysis.'}/><div className="flex flex-col gap-2"><button onClick={()=>input.current?.click()} className="rounded-xl border p-2.5" title="Attach files"><Paperclip className="size-4"/></button><button onClick={ask} disabled={busy||(!q.trim()&&!files.length)} className="rounded-xl bg-neutral-950 p-2.5 text-white disabled:opacity-40 dark:bg-white dark:text-neutral-950"><Send className="size-4"/></button></div></div>
 <input ref={input} type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.csv,.xlsx,.xls,.txt,.md,.json,.mp3,.wav,.mp4,.webm" onChange={e=>setFiles(v=>[...v,...Array.from(e.target.files||[])].slice(0,6))} className="hidden"/>
 <div className="mt-2 flex flex-wrap gap-2 text-[11px] text-neutral-400"><span>{ar?'جرّب: لخص، قارن، استخرج، أنشئ، احسب، أو نفّذ.':'Try: summarize, compare, extract, create, calculate, or apply.'}</span><Link href={'/'+locale+'/help'} className="underline">{ar?'دليل AI':'AI guide'}</Link></div>
 {answer&&<div className="mt-3 rounded-2xl border bg-neutral-50 p-4 dark:border-neutral-800 dark:bg-neutral-900"><p className="whitespace-pre-wrap text-sm leading-6">{answer.text}</p>{answer.action&&answer.action.type!=='none'&&<div className="mt-3 rounded-xl border bg-white p-3 dark:border-neutral-800 dark:bg-neutral-950"><div className="flex items-center gap-2 text-xs font-semibold"><CheckCircle2 className="size-4"/>{ar?'إجراء مقترح في SalesOS':'Suggested SalesOS action'}</div><div className="mt-1 text-xs text-neutral-500">{answer.action.type}</div><button onClick={apply} disabled={busy} className="mt-2 rounded-xl bg-neutral-950 px-3 py-2 text-xs text-white dark:bg-white dark:text-neutral-950">{ar?'نفّذ':'Apply'}</button></div>}{applied&&<p className="mt-2 text-xs text-emerald-600">{applied}</p>}</div>}</div></div></div></div>}
 </>;
}