'use client';
import Link from 'next/link';
import {FormEvent,useState} from 'react';
import {BookOpen,Send,Sparkles} from 'lucide-react';

async function parseResponse(r:Response){const raw=await r.text();try{return raw?JSON.parse(raw):{error:'Empty server response'}}catch{return{error:'Server returned non-JSON data (HTTP '+r.status+').'}}}

export function AssistantChat({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const [q,setQ]=useState('');const [files,setFiles]=useState<File[]>([]);const [answer,setAnswer]=useState<any>(null);const [busy,setBusy]=useState(false);
 const ask=async(e?:FormEvent)=>{e?.preventDefault();if(!q.trim()&&!files.length)return;setBusy(true);setAnswer(null);try{const f=new FormData();f.set('question',q);f.set('locale',locale);files.forEach(x=>f.append('files',x));const r=await fetch('/api/assistant',{method:'POST',body:f,headers:{accept:'application/json'}});const d=await parseResponse(r);setAnswer(r.ok?d:{mode:'error',error:d.error||'Request failed'})}catch(e){setAnswer({mode:'error',error:e instanceof Error?e.message:'Request failed'})}finally{setBusy(false)}};
 return <section className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-neutral-400">SalesOS</p><h1 className="mt-1 text-3xl font-semibold">{ar?'المساعد الذكي':'AI Copilot'}</h1><p className="mt-2 text-sm text-neutral-500">{ar?'Gemini يحلل بيانات SalesOS والملفات المرفوعة.':'Gemini analyzes SalesOS data and uploaded files.'}</p></div><Link href={'/'+locale+'/help'} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs"><BookOpen className="size-4"/>Help</Link></div><div className="flex flex-wrap gap-2"><button onClick={()=>setQ(ar?'ما الذي يحتاج انتباهي اليوم؟':'What needs my attention today?')} className="rounded-full border px-3 py-2 text-xs">✨ {ar?'ماذا اليوم؟':'What today?'}</button><button onClick={()=>setQ(ar?'حلل الـPipeline وأعطني الخطوة التالية':'Analyze the pipeline and give me the next action')} className="rounded-full border px-3 py-2 text-xs">⚡ {ar?'حلل الفرص':'Analyze pipeline'}</button></div><div className="rounded-2xl border border-dashed p-4"><input type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.csv,.xlsx,.xls,.txt,.md,.json,.mp3,.wav,.mp4,.webm" onChange={e=>{let total=0;const next=Array.from(e.target.files||[]).filter(f=>{if(total+f.size>3*1024*1024)return false;total+=f.size;return true}).slice(0,6);setFiles(next)}} className="w-full text-sm"/>{files.length>0&&<p className="mt-2 text-xs text-neutral-500">{files.length} {ar?'ملفات جاهزة للتحليل':'files ready for analysis'}</p>}</div><form onSubmit={ask} className="flex gap-2"><textarea value={q} onChange={e=>setQ(e.target.value)} rows={3} placeholder={ar?'اسأل، لخص، قارن، استخرج أو اطلب إنشاء عنصر في SalesOS...':'Ask, summarize, compare, extract, or request a SalesOS action...'} className="min-w-0 flex-1 rounded-2xl border bg-white px-4 py-3 dark:border-neutral-800 dark:bg-neutral-900"/><button disabled={busy||(!q.trim()&&!files.length)} className="inline-flex items-center gap-2 rounded-2xl bg-neutral-950 px-4 py-3 text-sm text-white disabled:opacity-50 dark:bg-white dark:text-neutral-950"><Send className="size-4"/>{busy?(ar?'يحلل...':'Analyzing...'):<Sparkles className="size-4"/>}</button></form>{answer&&<div className="rounded-3xl border bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-center gap-2 text-xs uppercase tracking-wide text-neutral-500"><Sparkles className="size-4"/>{answer.mode==='gemini'?(ar?'Gemini AI حقيقي':'Real Gemini AI'):answer.mode==='local'?(ar?'الوضع المحلي المجاني':'Free local mode'):'AI error'}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{answer.text||answer.error}</p>{answer.action&&answer.action.type!=='none'&&<p className="mt-3 rounded-xl border p-3 text-xs">{ar?'إجراء مقترح: ':'Suggested action: '}{answer.action.type}</p>}</div>}</section>
}