'use client';
import Link from 'next/link';
import {FormEvent,useState} from 'react';
import {BookOpen,Bot,Send,Sparkles} from 'lucide-react';
const prompts={ar:['ما الذي يحتاج انتباهي اليوم؟','كيف أحسب رواتب الفريق؟','كيف أضيف موظفاً؟','من المتأخر في السداد؟','كيف أصدر Excel؟'],en:['What needs my attention today?','How do I calculate payroll?','How do I add staff?','Who is overdue?','How do I export Excel?']};
export function AssistantChat({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const [q,setQ]=useState('');const [answer,setAnswer]=useState<any>(null);const [busy,setBusy]=useState(false);
 const ask=async(e?:FormEvent)=>{e?.preventDefault();if(!q.trim())return;setBusy(true);setAnswer(null);try{const r=await fetch('/api/assistant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:q,locale})});const d=await r.json();setAnswer(r.ok?d:{text:d.error||'Request failed',links:[]})}catch(e){setAnswer({text:e instanceof Error?e.message:'Request failed',links:[]})}finally{setBusy(false)}};
 return <div className="max-w-4xl"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-xl border p-2"><Bot className="size-5"/></span><div><h1 className="text-2xl font-semibold">{ar?'المساعد الذكي':'AI Copilot'}</h1><p className="text-xs text-neutral-500">{ar?'بيانات SalesOS مع نموذج حقيقي اختياري.':'SalesOS data with optional real-model support.'}</p></div></div><Link href={'/'+locale+'/help'} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs"><BookOpen className="size-4"/>Help</Link></div><div className="mt-5 flex flex-wrap gap-2">{prompts[locale].map(p=><button key={p} onClick={()=>setQ(p)} className="rounded-full border px-3 py-2 text-xs hover:bg-neutral-100 dark:hover:bg-neutral-800">{p}</button>)}</div><form onSubmit={ask} className="mt-4 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'اسأل عن المبيعات أو الموظفين أو الرواتب أو أي أداة...':'Ask about sales, staff, payroll, or any tool...'} className="min-w-0 flex-1 rounded-xl border bg-white px-4 py-3 dark:border-neutral-800 dark:bg-neutral-900"/><button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-3 text-sm text-white disabled:opacity-50 dark:bg-white dark:text-neutral-950"><Send className="size-4"/>{busy?(ar?'يفكر...':'Thinking...'):(ar?'اسأل':'Ask')}</button></form>{answer&&<div className="mt-5 rounded-3xl border bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-center gap-2 text-xs uppercase tracking-wide text-neutral-500"><Sparkles className="size-4"/>{answer.mode==='real'?(ar?'نموذج حقيقي':'Real model'):(ar?'وضع محلي مجاني':'Free local mode')}</div><p className="mt-3 whitespace-pre-wrap text-base leading-7">{answer.text}</p>{answer.links?.length>0&&<div className="mt-4 flex flex-wrap gap-2">{answer.links.map((l:any)=><Link key={l.href} href={'/'+locale+l.href} className="rounded-lg border px-3 py-1.5 text-xs">{l.label}</Link>)}</div>}</div>}</div>
}