'use client';
import {useEffect,useMemo,useState} from 'react';
import {Download,FileSpreadsheet,Lock,Play,ReceiptText,ShieldCheck,RefreshCw} from 'lucide-react';
import * as XLSX from 'xlsx';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,EmptyState,MetricCard,PageHeader,StatusPill} from '@/components/ui/primitives';
export default function PayrollDashboard({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId}=useOrg();const [runs,setRuns]=useState<any[]>([]);const [lines,setLines]=useState<any[]>([]);const [plans,setPlans]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [v,setV]=useState<any>({period:new Date().toISOString().slice(0,7),plan_id:''});const [error,setError]=useState('');
 const load=async()=>{if(!activeOrgId)return;const [r,l,p]=await Promise.all([s.from('payroll_runs').select('*').eq('org_id',activeOrgId).order('period',{ascending:false}),s.from('payroll_lines').select('*').eq('org_id',activeOrgId).order('created_at',{ascending:false}).limit(500),s.from('commission_plans').select('id,name').eq('org_id',activeOrgId).eq('active',true)]);setRuns(r.data||[]);setLines(l.data||[]);setPlans(p.data||[]);if(p.data?.[0]&&!v.plan_id)setV((x:any)=>({...x,plan_id:p.data[0].id}))};
 useEffect(()=>{load()},[activeOrgId,s]);
 const createRun=async()=>{if(!activeOrgId||!v.plan_id)return;setBusy(true);setError('');const period=v.period+'-01';const {data:run,error:e}=await s.from('payroll_runs').insert({org_id:activeOrgId,period,status:'draft'}).select('id').single();if(e||!run){setError(e?.message||'Unable to create run');setBusy(false);return}const {data:count,error:ce}=await s.rpc('calculate_payroll_run',{p_run_id:run.id,p_plan_id:v.plan_id});if(ce){await s.from('payroll_runs').delete().eq('id',run.id);setError(ce.message)}else setError(ar?'تم حساب '+count+' سطر تلقائياً.':'Automatically calculated '+count+' payroll lines.');setBusy(false);load()};
 const approve=async(id:string)=>{setBusy(true);const {error}=await s.rpc('approve_payroll_run',{p_run_id:id});setError(error?.message||'');setBusy(false);load()};
 const lock=async(id:string)=>{if(!confirm(ar?'قفل التشغيل؟':'Lock this payroll run?'))return;setBusy(true);const {error}=await s.rpc('lock_payroll_run',{p_run_id:id});setError(error?.message||'');setBusy(false);load()};
 const exportXlsx=()=>{const run=runs[0];if(!run)return;const data=lines.filter(l=>l.run_id===run.id).map(l=>({Rep:l.rep_id,Salary:l.basic_salary,Sales:l.net_sales,Target:l.target,AchievementPct:Number(l.achievement||0)*100,GP:l.gross_profit,GPpct:Number(l.gp_pct||0)*100,CommissionRate:l.commission_rate,FinalCommission:l.final_commission,KPI:l.kpi_score,KPIsBonus:l.kpi_bonus,CollectionPct:Number(l.collection_pct||0)*100,Gate:l.collection_gate,TotalGross:l.total_gross}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'Payroll');XLSX.writeFile(wb,'salesos-payroll.xlsx')};
 const selected=runs[0];const selectedLines=selected?lines.filter(l=>l.run_id===selected.id):[];const total=selectedLines.reduce((n,l)=>n+Number(l.total_gross||0),0);
 return <section className="space-y-6 p-4 md:p-7"><PageHeader eyebrow={ar?'المالية والأجور':'Payroll'} title={ar?'الرواتب والعمولات الذكية':'Smart payroll & commissions'} description={ar?'يجمع المبيعات والهدف والهامش والتحصيل وKPI تلقائياً.':'Sales, target, margin, collections and KPI are collected automatically.'} actions={selected&&<button onClick={exportXlsx} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2.5 text-sm"><Download className="size-4"/>Excel</button>}/><Card className="p-5"><div className="grid gap-3 md:grid-cols-2"><input type="month" value={v.period} onChange={e=>setV({...v,period:e.target.value})} className="rounded-xl border px-3 py-2.5"/><select value={v.plan_id} onChange={e=>setV({...v,plan_id:e.target.value})} className="rounded-xl border bg-transparent px-3 py-2.5"><option value="">{ar?'خطة العمولة':'Commission plan'}</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><button onClick={createRun} disabled={busy||!v.plan_id} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm text-white disabled:opacity-50 dark:bg-white dark:text-neutral-950"><Play className="size-4"/>{busy?(ar?'الحساب...':'Calculating...'):(ar?'حساب الرواتب تلقائياً':'Calculate automatically')}</button>{error&&<p className="mt-3 text-sm text-neutral-500">{error}</p>}</Card><div className="grid gap-3 md:grid-cols-4"><MetricCard label={ar?'التشغيلات':'Runs'} value={runs.length} icon={<ReceiptText className="size-4"/>}/><MetricCard label={ar?'آخر السطور':'Latest lines'} value={selectedLines.length} icon={<FileSpreadsheet className="size-4"/>}/><MetricCard label={ar?'الإجمالي':'Gross total'} value={total.toLocaleString()+' EGP'} icon={<ShieldCheck className="size-4"/>}/><MetricCard label={ar?'الحالة':'Status'} value={selected?.status||'—'} icon={<RefreshCw className="size-4"/>}/></div><Card className="overflow-hidden"><div className="border-b p-5"><div className="flex items-center gap-2"><Lock className="size-4"/><h2 className="font-semibold">{ar?'دورات الرواتب':'Payroll runs'}</h2></div></div><div className="divide-y">{runs.map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 p-4"><div className="flex-1"><div className="font-medium">{r.period}</div><div className="text-xs text-neutral-500">{r.created_at}</div></div><StatusPill status={r.status}/>{r.status==='calculated'&&<button onClick={()=>approve(r.id)} disabled={busy} className="rounded-xl border px-3 py-2 text-xs">{ar?'اعتماد':'Approve'}</button>}{r.status==='approved'&&<button onClick={()=>lock(r.id)} disabled={busy} className="rounded-xl border px-3 py-2 text-xs">{ar?'قفل':'Lock'}</button>}</div>)}{runs.length===0&&<EmptyState title={ar?'لا توجد تشغيلات':'No payroll runs'} description={ar?'شغّل الشهر وسيتم الحساب من بيانات الفريق.':'Run a month and calculations will come from team data.'}/>}</div></Card></section>
}