'use client';
import {useEffect,useMemo,useState} from 'react';
import {Calculator,Lock,Play,ReceiptText} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,EmptyState,MetricCard,PageHeader,StatusPill} from '@/components/ui/primitives';

export default function PayrollDashboard({locale}:{locale:'ar'|'en'}){const ar=locale==='ar';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId}=useOrg();const [runs,setRuns]=useState<any[]>([]);const [lines,setLines]=useState<any[]>([]);const [plans,setPlans]=useState<any[]>([]);const [v,setV]=useState<any>({period:new Date().toISOString().slice(0,7),plan_id:'',kpi_score:'80',collection_pct:'1'});const load=async()=>{if(!activeOrgId)return;const [r,l,p]=await Promise.all([s.from('payroll_runs').select('*').eq('org_id',activeOrgId).order('created_at',{ascending:false}),s.from('payroll_lines').select('*').eq('org_id',activeOrgId).order('created_at',{ascending:false}).limit(100),s.from('commission_plans').select('id,name').eq('org_id',activeOrgId).eq('active',true)]);setRuns(r.data||[]);setLines(l.data||[]);setPlans(p.data||[]);if(p.data?.[0]&&!v.plan_id)setV((x:any)=>({...x,plan_id:p.data[0].id}))};useEffect(()=>{load()},[activeOrgId,s]);
const createRun=async()=>{if(!activeOrgId||!v.plan_id)return;const period=v.period.length===7?v.period+'-01':v.period;const {data:run,error}=await s.from('payroll_runs').insert({org_id:activeOrgId,period,status:'draft'}).select('id').single();if(error||!run)return;const {data:reps}=await s.from('v_rep_month').select('*').eq('org_id',activeOrgId);for(const rep of reps||[]){const {data:calc}=await s.rpc('calculate_commission',{p_plan:v.plan_id,p_net_sales:Number(rep.sales||0),p_target:Number(rep.target||0),p_gp:Number(rep.gp||0),p_kpi_score:Number(v.kpi_score),p_collection_pct:Number(v.collection_pct)});const x=calc||{};await s.from('payroll_lines').insert({org_id:activeOrgId,run_id:run.id,rep_id:rep.rep_id,basic_salary:0,target:Number(rep.target||0),net_sales:Number(rep.sales||0),achievement:Number(rep.achievement||0),gross_profit:Number(rep.gp||0),gp_pct:Number(rep.gp_pct||0),commission_rate:Number(x.rate||0),base_commission:Number(x.base_commission||0),gp_factor:Number(x.gp_factor||0),final_commission:Number(x.final_commission||0),kpi_score:Number(v.kpi_score||0),kpi_bonus:Number(x.kpi_bonus||0),collection_pct:Number(v.collection_pct||0),collection_gate:x.collection_gate||'review',total_variable:Number(x.final_commission||0)+Number(x.kpi_bonus||0),total_gross:Number(x.final_commission||0)+Number(x.kpi_bonus||0),snapshot:x,notes:null})}load()};
const selectedLines=lines.filter(l=>runs[0]?.id===l.run_id);const total=selectedLines.reduce((n,l)=>n+Number(l.total_gross||0),0);
return <section className="space-y-6 p-4 md:p-7"><PageHeader eyebrow={ar?'المالية والأجور':'Payroll'} title={ar?'الرواتب والعمولات':'Payroll & commissions'} description={ar?'تشغيل شهر الرواتب، حساب العمولة من المبيعات والهامش وKPI والتحصيل، ثم مراجعة وقفل التشغيل.':'Run payroll from sales, GP, KPI, and collection data, then review and lock the run.'}/><Card className="p-5"><div className="grid gap-3 md:grid-cols-4"><input type="month" value={v.period} onChange={e=>setV({...v,period:e.target.value})} className="rounded-xl border px-3 py-2.5"/><select value={v.plan_id} onChange={e=>setV({...v,plan_id:e.target.value})} className="rounded-xl border bg-transparent px-3 py-2.5"><option value="">{ar?'خطة العمولة':'Commission plan'}</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="number" min="0" max="100" value={v.kpi_score} onChange={e=>setV({...v,kpi_score:e.target.value})} placeholder="KPI" className="rounded-xl border px-3 py-2.5"/><input type="number" min="0" max="1" step="0.01" value={v.collection_pct} onChange={e=>setV({...v,collection_pct:e.target.value})} placeholder="Collection %" className="rounded-xl border px-3 py-2.5"/></div><button onClick={createRun} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm text-white dark:bg-white dark:text-neutral-950"><Play className="size-4"/>{ar?'تشغيل شهر الرواتب':'Run payroll'}</button></Card><div className="grid gap-3 md:grid-cols-3"><MetricCard label={ar?'تشغيلات الرواتب':'Payroll runs'} value={runs.length} icon={<ReceiptText className="size-4"/>}/><MetricCard label={ar?'سطور آخر تشغيل':'Latest run lines'} value={selectedLines.length} icon={<Calculator className="size-4"/>}/><MetricCard label={ar?'إجمالي المتغير':'Latest variable total'} value={total.toLocaleString()+' EGP'} icon={<ReceiptText className="size-4"/>}/></div><Card className="overflow-hidden"><div className="border-b p-5"><div className="flex items-center gap-2"><Lock className="size-4"/><h2 className="font-semibold">{ar?'تشغيلات الرواتب':'Payroll runs'}</h2></div></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-neutral-50 dark:bg-neutral-950"><tr><th className="px-4 py-3 text-start">Period</th><th className="px-4 py-3 text-start">Status</th><th className="px-4 py-3 text-start">Created</th><th className="px-4 py-3 text-start">Approved</th></tr></thead><tbody>{runs.map(r=><tr key={r.id} className="border-b last:border-0 dark:border-neutral-800"><td className="px-4 py-3">{r.period}</td><td className="px-4 py-3"><StatusPill status={r.status}/></td><td className="px-4 py-3">{r.created_at}</td><td className="px-4 py-3">{r.approved_at||'—'}</td></tr>)}</tbody></table>{runs.length===0&&<EmptyState title={ar?'لا توجد تشغيلات':'No payroll runs'} description={ar?'شغّل أول شهر لإنشاء السطور.':'Run the first payroll period to generate lines.'}/>}</div></Card></section>}
