'use client';
import {useEffect,useMemo,useState} from 'react';
import {Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Download,FileBarChart,RefreshCw} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,MetricCard,PageHeader} from '@/components/ui/primitives';
export default function ReportsDashboard({locale}:{locale:'ar'|'en'}){const ar=locale==='ar';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId}=useOrg();const [rows,setRows]=useState<any[]>([]);const [summary,setSummary]=useState<any>({sales:0,collection:0,pipeline:0,customers:0});const [busy,setBusy]=useState(false);
const load=async()=>{if(!activeOrgId)return;setBusy(true);const year=new Date().getFullYear();const start=year+'-01-01';const [inv,pay,deal,acc]=await Promise.all([s.from('invoices').select('issue_date,total,status').eq('org_id',activeOrgId).gte('issue_date',start).neq('status','void'),s.from('payments').select('payment_date,amount').eq('org_id',activeOrgId).eq('status','received').gte('payment_date',start),s.from('deals').select('value,status').eq('org_id',activeOrgId),s.from('accounts').select('*',{count:'exact',head:true}).eq('org_id',activeOrgId)]);const months=Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0'));const chart=months.map(m=>{const sale=(inv.data||[]).filter((x:any)=>String(x.issue_date).slice(5,7)===m).reduce((n:number,x:any)=>n+Number(x.total||0),0);const collection=(pay.data||[]).filter((x:any)=>String(x.payment_date).slice(5,7)===m).reduce((n:number,x:any)=>n+Number(x.amount||0),0);return {month:m,sales:sale,collection}});setRows(chart);setSummary({sales:(inv.data||[]).reduce((n:number,x:any)=>n+Number(x.total||0),0),collection:(pay.data||[]).reduce((n:number,x:any)=>n+Number(x.amount||0),0),pipeline:(deal.data||[]).filter((x:any)=>x.status==='open').reduce((n:number,x:any)=>n+Number(x.value||0),0),customers:acc.count||0});setBusy(false)};useEffect(()=>{load()},[activeOrgId,s]);
const exportCsv=()=>{const body=['month,sales,collection',...rows.map(r=>[r.month,r.sales,r.collection].join(','))].join('\n');const b=new Blob([body],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='salesos-report.csv';a.click();URL.revokeObjectURL(a.href)};
return <section className="space-y-6 p-4 md:p-7"><PageHeader eyebrow={ar?'التحليلات':'Analytics'} title={ar?'مركز التقارير':'Reports center'} description={ar?'تقارير المبيعات والتحصيل والـPipeline مع تصدير CSV مجاني.':'Sales, collections, and pipeline reporting with free CSV export.'} actions={<><button onClick={load} className="rounded-xl border px-3 py-2.5 text-sm"><RefreshCw className="me-2 inline size-4"/>{ar?'تحديث':'Refresh'}</button><button onClick={exportCsv} className="rounded-xl bg-neutral-950 px-3 py-2.5 text-sm text-white dark:bg-white dark:text-neutral-950"><Download className="me-2 inline size-4"/>{ar?'تصدير CSV':'Export CSV'}</button></>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label={ar?'المبيعات YTD':'YTD sales'} value={summary.sales.toLocaleString()+' EGP'} icon={<FileBarChart className="size-4"/>}/><MetricCard label={ar?'التحصيل YTD':'YTD collection'} value={summary.collection.toLocaleString()+' EGP'}/><MetricCard label={ar?'الـPipeline':'Open pipeline'} value={summary.pipeline.toLocaleString()+' EGP'}/><MetricCard label={ar?'العملاء':'Customers'} value={summary.customers}/></div><Card className="p-5"><div className="mb-4"><h2 className="font-semibold">{ar?'المبيعات والتحصيل حسب الشهر':'Sales & collection by month'}</h2><p className="mt-1 text-xs text-neutral-500">{ar?'السنة الحالية':'Current year'}</p></div><div className="h-80">{rows.length&& !busy?<ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="sales" fill="currentColor" fillOpacity={0.7}/><Bar dataKey="collection" fill="currentColor" fillOpacity={0.3}/></BarChart></ResponsiveContainer>:<div className="flex h-full items-center justify-center text-sm text-neutral-500">{ar?'لا توجد بيانات بعد.':'No data yet.'}</div>}</div></Card><div className="grid gap-3 md:grid-cols-3">{['daily','weekly','category'].map(k=><a key={k} href={'/'+locale+'/reports/'+k} className="rounded-2xl border bg-white p-4 text-sm hover:shadow-sm dark:border-neutral-800 dark:bg-neutral-900"><div className="font-medium capitalize">{k} report</div><div className="mt-1 text-xs text-neutral-500">{ar?'تقرير تشغيلي قابل للتفصيل':'Operational report view'}</div></a>)}</div></section>}
