'use client';
import {useEffect,useMemo,useState} from 'react';
import {CalendarCheck,Clock3,UserRound,Users} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,EmptyState,MetricCard,PageHeader,StatusPill} from '@/components/ui/primitives';

export default function WorkforceDashboard({locale}:{locale:'ar'|'en'}){const ar=locale==='ar';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId,userId}=useOrg();const [reps,setReps]=useState<any[]>([]);const [attendance,setAttendance]=useState<any[]>([]);const [v,setV]=useState<any>({status:'present',notes:''});
const load=async()=>{if(!activeOrgId)return;const d=new Date();const month=d.toISOString().slice(0,7);const [{data:r},{data:a}]=await Promise.all([s.from('reps').select('id,profile_id,sales_type,basic_salary,hire_date,active,profiles(id,full_name)').eq('org_id',activeOrgId).order('created_at'),s.from('attendance').select('*').eq('org_id',activeOrgId).gte('work_date',month+'-01').order('work_date',{ascending:false}).limit(50)]);setReps(r||[]);setAttendance(a||[])};
useEffect(()=>{load()},[activeOrgId,s]);
const clockIn=async(rep:any)=>{if(!activeOrgId)return;await s.from('attendance').insert({org_id:activeOrgId,user_id:rep.profile_id,work_date:new Date().toISOString().slice(0,10),clock_in:new Date().toISOString(),status:'present',notes:v.notes||null});load()};
const today=new Date().toISOString().slice(0,10);const present=attendance.filter(a=>a.work_date===today&&a.status==='present').length;const active= reps.filter(r=>r.active).length;
return <section className="space-y-6 p-4 md:p-7"><PageHeader eyebrow={ar?'الأشخاص':'People'} title={ar?'الموارد البشرية':'HR & attendance'} description={ar?'حضور المندوبين، القوة العاملة، وحالة الدوام من مساحة واحدة.':'Workforce roster, attendance, and daily status in one workspace.'}/><div className="grid gap-3 md:grid-cols-3"><MetricCard label={ar?'المندوبون النشطون':'Active reps'} value={active} icon={<Users className="size-4"/>}/><MetricCard label={ar?'حاضر اليوم':'Present today'} value={present} icon={<CalendarCheck className="size-4"/>}/><MetricCard label={ar?'سجلات هذا الشهر':'Month attendance records'} value={attendance.length} icon={<Clock3 className="size-4"/>}/></div><Card className="overflow-hidden"><div className="border-b p-5 dark:border-neutral-800"><h2 className="font-semibold">{ar?'قائمة المندوبين':'Rep roster'}</h2><p className="mt-1 text-xs text-neutral-500">{ar?'يمكن تسجيل الحضور مباشرة من هنا.':'Clock attendance from the roster.'}</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-neutral-50 dark:border-neutral-800 dark:bg-neutral-950"><tr><th className="px-4 py-3 text-start">Rep</th><th className="px-4 py-3 text-start">Type</th><th className="px-4 py-3 text-start">Hire date</th><th className="px-4 py-3 text-start">Today</th><th className="px-4 py-3 text-end"/></tr></thead><tbody>{reps.map(r=>{const a=attendance.find(x=>x.work_date===today&&x.user_id===r.profile_id);return <tr key={r.id} className="border-b last:border-0 dark:border-neutral-800"><td className="px-4 py-3"><div className="flex items-center gap-2"><span className="rounded-xl border p-2"><UserRound className="size-4"/></span><div><div className="font-medium">{r.profiles?.full_name||r.profile_id}</div><div className="text-xs text-neutral-500">{r.profile_id}</div></div></div></td><td className="px-4 py-3">{r.sales_type}</td><td className="px-4 py-3">{r.hire_date||'—'}</td><td className="px-4 py-3">{a?<StatusPill status={a.status}/>:<span className="text-xs text-neutral-400">{ar?'غير مسجل':'Not clocked'}</span>}</td><td className="px-4 py-3 text-end">{!a&&r.profile_id&&<button onClick={()=>clockIn(r)} className="rounded-xl border px-3 py-2 text-xs">{ar?'تسجيل حضور':'Clock in'}</button>}</td></tr>})}</tbody></table>{reps.length===0&&<EmptyState title={ar?'لا يوجد مندوبون':'No reps'} description={ar?'أضف المندوبين من إدارة الفريق.':'Add reps from team management.'}/>}</div></Card></section>}
