'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {BookOpen,Search,Sparkles} from 'lucide-react';
import {HELP_ARTICLES} from '@/lib/help/articles';
export function HelpCenter({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const [q,setQ]=useState('');const [open,setOpen]=useState('start');
 const filtered=useMemo(()=>{const t=q.trim().toLowerCase();if(!t)return HELP_ARTICLES;return HELP_ARTICLES.filter(a=>[a.titleAr,a.titleEn,a.bodyAr,a.bodyEn,...a.keywords].join(' ').toLowerCase().includes(t))},[q]);
 const selected=filtered.find(a=>a.id===open)||filtered[0];
 return <section className="space-y-6 p-4 md:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-neutral-400">SalesOS</p><h1 className="mt-1 text-3xl font-semibold">{ar?'مركز المساعدة':'Help center'}</h1><p className="mt-2 max-w-2xl text-sm text-neutral-500">{ar?'دليل عملي يشرح ماذا تفعل ولماذا.':'Practical guidance for what to do and why.'}</p></div><Link href={'/'+locale+'/assistant'} className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm text-white dark:bg-white dark:text-neutral-950"><Sparkles className="size-4"/>{ar?'اسأل المساعد':'Ask AI'}</Link></div><div className="relative"><Search className="absolute start-3 top-3 size-4 text-neutral-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث في الدليل...':'Search the guide...'} className="w-full rounded-2xl border bg-white py-3 ps-10 pe-4 text-sm dark:border-neutral-800 dark:bg-neutral-900"/></div><div className="grid gap-4 lg:grid-cols-[280px_1fr]"><div className="space-y-2">{filtered.map(a=><button key={a.id} onClick={()=>setOpen(a.id)} className={"w-full rounded-xl border p-3 text-start "+(selected?.id===a.id?'bg-neutral-950 text-white dark:bg-white dark:text-neutral-950':'bg-white dark:border-neutral-800 dark:bg-neutral-900')}><div className="text-sm font-medium">{ar?a.titleAr:a.titleEn}</div><div className="mt-1 text-[11px] opacity-60">{a.category}</div></button>)}</div><article className="rounded-3xl border bg-white p-6 dark:border-neutral-800 dark:bg-neutral-900"><BookOpen className="size-5"/>{selected&&<><h2 className="mt-4 text-2xl font-semibold">{ar?selected.titleAr:selected.titleEn}</h2><p className="mt-3 text-sm leading-7 text-neutral-600 dark:text-neutral-300">{ar?selected.bodyAr:selected.bodyEn}</p><div className="mt-6 space-y-2">{(ar?selected.stepsAr:selected.stepsEn).map((step,i)=><div key={step} className="flex gap-3 rounded-xl border p-3"><span className="flex size-6 shrink-0 items-center justify-center rounded-full border text-xs">{i+1}</span><span className="text-sm">{step}</span></div>)}</div></>}</article></div></section>
}