'use client';

import {useEffect,useMemo,useState} from 'react';
import {Calculator,RefreshCw} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';

export default function Payroll(){
 const p=typeof window!=='undefined'?window.location.pathname:'/ar/payroll';const locale=p.split('/')[1]||'ar';const ar=locale!=='en';
 const s=useMemo(()=>createClient(),[]);const {activeOrgId}=useOrg();
 const [plans,setPlans]=useState<any[]>([]);const [reps,setReps]=useState<any[]>([]);const [plan,setPlan]=useState('');const [rep,setRep]=useState('');
 const [values,setValues]=useState({target:'100000',sales:'80000',gp:'12000',kpi:'80',collection:'1'});const [result,setResult]=useState<any>(null);const [loading,setLoading]=useState(false);
 useEffect(()=>{(async()=>{if(!activeOrgId)return;const [{data:p},{data:r}]=await Promise.all([s.from('commission_plans').select('id,name,formula_type').eq('org_id',activeOrgId).eq('active',true).order('name'),s.from('reps').select('id,profile_id,sales_type').eq('org_id',activeOrgId).eq('active',true).order('created_at')]);setPlans(p??[]);setReps(r??[]);if(p?.[0])setPlan(p[0].id);if(r?.[0])setRep(r[0].id)})()},[activeOrgId,s]);
 const calc=async()=>{if(!plan)return;setLoading(true);const {data,error}=await s.rpc('calculate_commission',{p_plan:plan,p_net_sales:Number(values.sales),p_target:Number(values.target),p_gp:Number(values.gp),p_kpi_score:Number(values.kpi),p_collection_pct:Number(values.collection)});setResult(error?{error:error.message}:data);setLoading(false)};
 return <section className="p-4 md:p-8 space-y-6"><div><h1 className="text-2xl font-semibold">{ar?'الرواتب والعمولات':'Payroll & commissions'}</h1><p className="mt-1 text-sm text-neutral-500">{ar?'حساب العمولة مع بوابة التحصيل وعامل هامش الربح وKPI.':'Commission calculation with collection gate, GP factor, and KPI bonus.'}</p></div>
 <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-center gap-2 font-semibold"><Calculator className="size-5"/>{ar?'حاسبة العمولة':'Commission calculator'}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm"><span className="mb-1 block">{ar?'الخطة':'Plan'}</span><select value={plan} onChange={e=>setPlan(e.target.value)} className="w-full rounded-xl border bg-transparent px-3 py-2.5">{plans.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm"><span className="mb-1 block">Rep</span><select value={rep} onChange={e=>setRep(e.target.value)} className="w-full rounded-xl border bg-transparent px-3 py-2.5"><option value="">—</option>{reps.map(x=><option key={x.id} value={x.id}>{x.id} · {x.sales_type}</option>)}</select></label>{Object.entries(values).map(([k,v])=><label key={k} className="text-sm"><span className="mb-1 block">{k==='target'?'Target':k==='sales'?'Net sales':k==='gp'?'Gross profit':k==='kpi'?'KPI score':'Collection % (1.0 = 100%)'}</span><input type="number" step="0.01" value={v} onChange={e=>setValues(x=>({...x,[k]:e.target.value}))} className="w-full rounded-xl border px-3 py-2.5"/></label>)}</div><button onClick={calc} disabled={loading||!plan} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm text-white disabled:opacity-50 dark:bg-white dark:text-neutral-950"><RefreshCw className="size-4"/>{loading?(ar?'حساب...':'Calculating...'):(ar?'احسب':'Calculate')}</button>{result&&<pre className="mt-4 overflow-auto rounded-xl bg-neutral-950 p-4 text-xs text-white">{JSON.stringify(result,null,2)}</pre>}</div>
 <div className="rounded-2xl border bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><h2 className="font-semibold">{ar?'خطط العمولات':'Commission plans'}</h2><div className="mt-4 space-y-3">{plans.map(x=><div key={x.id} className="rounded-xl border p-3 dark:border-neutral-800"><div className="flex justify-between"><span className="font-medium">{x.name}</span><span className="text-xs text-neutral-500">{x.formula_type}</span></div></div>)}{plans.length===0&&<p className="text-sm text-neutral-500">{ar?'لم يتم إنشاء خطط بعد.':'No plans yet.'}</p>}</div></div></div>
 </section>
}
