import type {ModuleManifest} from './types';

export const generatedModuleCatalog:ModuleManifest[]=[
 {id:'sales',name:'Sales',version:'1.0.0',enabledByDefault:true,nav:[{label:'Sales',href:'/sales'}]},
 {id:'accounts',name:'Accounts',version:'1.0.0',enabledByDefault:true,nav:[{label:'Accounts',href:'/accounts'}]},
 {id:'contacts',name:'Contacts',version:'1.0.0',enabledByDefault:true,nav:[{label:'Contacts',href:'/contacts'}]},
 {id:'leads',name:'Leads',version:'1.0.0',enabledByDefault:true,nav:[{label:'Leads',href:'/leads'}]},
 {id:'deals',name:'Deals',version:'1.0.0',enabledByDefault:true,nav:[{label:'Deals',href:'/deals'}]},
 {id:'pipeline',name:'Pipeline',version:'1.0.0',enabledByDefault:true,nav:[{label:'Pipeline',href:'/pipeline'}]},
 {id:'activities',name:'Activities',version:'1.0.0',enabledByDefault:true,nav:[{label:'Activities',href:'/activities'}]},
 {id:'collections',name:'Collections',version:'1.0.0',enabledByDefault:true,nav:[{label:'Collections',href:'/collections'}]},
 {id:'targets',name:'Targets',version:'1.0.0',enabledByDefault:true,nav:[{label:'Targets',href:'/targets'}]},
 {id:'tasks',name:'Tasks',version:'1.0.0',enabledByDefault:true,nav:[{label:'Tasks',href:'/tasks'}]},
 {id:'products',name:'Products',version:'1.0.0',enabledByDefault:true,nav:[{label:'Products',href:'/products'}]},
 {id:'regions',name:'Regions',version:'1.0.0',enabledByDefault:true,nav:[{label:'Regions',href:'/regions'}]},
 {id:'teams',name:'Teams',version:'1.0.0',enabledByDefault:true,nav:[{label:'Teams',href:'/teams'}]},
 {id:'reps',name:'Sales Reps',version:'1.0.0',enabledByDefault:true,nav:[{label:'Sales Reps',href:'/reps'}]},
 {id:'finance',name:'Finance',version:'1.0.0',enabledByDefault:true,nav:[{label:'Finance',href:'/finance'}]},
 {id:'hr',name:'HR',version:'1.0.0',enabledByDefault:true,nav:[{label:'HR',href:'/hr'}]},
 {id:'team',name:'Team',version:'1.0.0',enabledByDefault:true,nav:[{label:'Team',href:'/team'}]},
 {id:'kpi',name:'KPI',version:'1.0.0',enabledByDefault:true,nav:[{label:'KPI',href:'/kpi'}]},
 {id:'performance',name:'Performance',version:'1.0.0',enabledByDefault:true,nav:[{label:'Performance',href:'/performance'}]},
 {id:'payroll',name:'Payroll',version:'1.0.0',enabledByDefault:true,nav:[{label:'Payroll',href:'/payroll'}]},
 {id:'reports',name:'Reports',version:'1.0.0',enabledByDefault:true,nav:[{label:'Reports',href:'/reports'}]},
 {id:'import',name:'Import',version:'1.0.0',enabledByDefault:true,nav:[{label:'Import',href:'/import'}]},
 {id:'alerts',name:'Alerts',version:'1.0.0',enabledByDefault:true,nav:[{label:'Alerts',href:'/alerts'}]},
 {id:'assistant',name:'Assistant',version:'1.0.0',enabledByDefault:true,nav:[{label:'Assistant',href:'/assistant'}]},
 {id:'extensions',name:'Extensions',version:'1.0.0',enabledByDefault:true,nav:[{label:'Extensions',href:'/extensions'}]},
 {id:'settings',name:'Settings',version:'1.0.0',enabledByDefault:true,nav:[{label:'Settings',href:'/settings'}]},
];
