import {LoginForm} from '@/components/auth/login-form';
import {ArrowRight,BarChart3,Boxes,ShieldCheck,Sparkles,Zap} from 'lucide-react';

export default async function LoginPage({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params;const safe=locale==='en'?'en':'ar';const ar=safe==='ar';
 const features=[
  [Zap,ar?'بيع وتحصيل سريع من الهاتف':'Fast sale and collection entry'],
  [BarChart3,ar?'لوحات وتحليلات مباشرة':'Live dashboards and analytics'],
  [ShieldCheck,ar?'صلاحيات وRLS على مستوى البيانات':'Data-level roles and RLS'],
  [Sparkles,ar?'مساعد مجاني من بياناتك':'Free data-grounded assistant'],
 ];
 return <main className="min-h-screen bg-neutral-950 text-white"><div className="mx-auto grid min-h-screen max-w-[1500px] lg:grid-cols-[1fr_520px]"><section className="hidden border-e border-white/10 p-10 lg:flex lg:flex-col lg:justify-between"><div><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-2xl bg-white text-neutral-950"><Boxes className="size-5"/></span><span className="text-lg font-semibold">SalesOS</span><span className="rounded-full border border-white/15 px-2 py-1 text-[10px] text-white/60">{ar?'النسخة المجانية':'Free stack'}</span></div><div className="mt-24 max-w-2xl"><p className="text-sm text-white/50">{ar?'مساحة قيادة المبيعات والعمليات':'Sales & operations command center'}</p><h1 className="mt-4 text-6xl font-semibold tracking-tight">{ar?'من البيانات إلى الإجراء.':'From data to action.'}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/60">{ar?'مكان واحد للمبيعات والعملاء والتحصيل والـPipeline والأهداف والـKPI والرواتب والتقارير، مع أدوات يومية سريعة للمندوب والمدير.':'One workspace for sales, customers, collections, pipeline, targets, KPI, payroll, and reporting—with fast workflows for reps and managers.'}</p></div><div className="mt-14 grid gap-3 sm:grid-cols-2">{features.map(([Icon,label]: any)=><div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><Icon className="size-5 text-white/70"/><div className="mt-5 text-sm text-white/80">{label}</div></div>)}</div></div><div className="flex items-center justify-between text-xs text-white/40"><span>{ar?'Arabic RTL + English LTR':'Arabic RTL + English LTR'}</span><span>{ar?'بدون خدمات مدفوعة مطلوبة':'No paid service required by default'}</span></div></section><section className="flex items-center justify-center bg-neutral-50 p-6 text-neutral-950 dark:bg-neutral-900 dark:text-white lg:p-12"><div className="w-full max-w-md"><div className="mb-8 lg:hidden"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-2xl bg-neutral-950 text-white dark:bg-white dark:text-neutral-950"><Boxes className="size-5"/></span><span className="text-lg font-semibold">SalesOS</span></div><h1 className="mt-6 text-3xl font-semibold">{ar?'منصة المبيعات والعمليات':'Sales & operations workspace'}</h1><p className="mt-2 text-sm text-neutral-500">{ar?'سجّل الدخول لفتح مساحة العمل.':'Sign in to open your workspace.'}</p></div><LoginForm locale={safe}/><a href={'/'+(ar?'en':'ar')+'/login'} className="mt-5 inline-flex items-center gap-2 text-xs text-neutral-500 hover:text-neutral-900 dark:hover:text-white">{ar?'English':'العربية'}<ArrowRight className="size-3"/></a></div></section></div></main>;
}
