'use client';

import {useEffect,useState} from 'react';
import {Copy,KeyRound,Plus,RotateCcw,ShieldCheck} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';

async function sha256(value:string){
 const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('');
}
function randomKey(){
 const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);
 return 'sos_live_'+Array.from(bytes).map(x=>x.toString(16).padStart(2,'0')).join('');
}

export default function ApiKeyManager({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const s=createClient() as any;const {activeOrgId}=useOrg();const [keys,setKeys]=useState<any[]>([]);const [name,setName]=useState('');const [raw,setRaw]=useState('');const [message,setMessage]=useState('');
 const load=async()=>{if(!activeOrgId)return;const {data,error}=await s.from('api_keys').select('id,name,key_prefix,scopes,last_used_at,revoked_at,created_at').eq('org_id',activeOrgId).order('created_at',{ascending:false});if(error)setMessage(error.message);else setKeys(data||[])};useEffect(()=>{load()},[activeOrgId]);
 const create=async()=>{if(!activeOrgId||!name.trim())return;const key=randomKey();const hash=await sha256(key);const {error}=await s.from('api_keys').insert({org_id:activeOrgId,name:name.trim(),key_prefix:key.slice(0,18),key_hash:hash,scopes:['read'],created_by:(await s.auth.getUser()).data.user?.id});if(error)setMessage(error.message);else{setRaw(key);setName('');setMessage(ar?'تم إنشاء المفتاح. انسخه الآن؛ لن يظهر كاملاً مرة أخرى.':'Key created. Copy it now; the full key will not be shown again.');load()}};
 const revoke=async(id:string)=>{if(!confirm(ar?'إلغاء المفتاح؟':'Revoke this key?'))return;await s.from('api_keys').update({revoked_at:new Date().toISOString()}).eq('id',id).eq('org_id',activeOrgId);load()};
 const copy=async()=>{if(raw){await navigator.clipboard.writeText(raw);setMessage(ar?'تم النسخ.':'Copied.')}};
 return <section className="space-y-6"><div className="flex items-start gap-3"><span className="flex size-10 items-center justify-center rounded-xl border"><KeyRound className="size-5"/></span><div><h2 className="text-xl font-semibold">{ar?'مفاتيح API':'API keys'}</h2><p className="mt-1 text-sm text-neutral-500">{ar?'تكاملات قراءة فقط مع SalesOS بدون كشف مفاتيح قاعدة البيانات.':'Read-only integrations without exposing database credentials.'}</p></div></div><div className="rounded-2xl border bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><input value={name} onChange={e=>setName(e.target.value)} placeholder={ar?'اسم التطبيق أو التكامل':'Application or integration name'} className="rounded-xl border px-3 py-2.5"/><button onClick={create} className="inline-flex items-center justify-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm text-white dark:bg-white dark:text-neutral-950"><Plus className="size-4"/>{ar?'إنشاء مفتاح':'Create key'}</button></div>{raw&&<div className="mt-4 rounded-xl border bg-neutral-50 p-4 dark:border-neutral-800 dark:bg-neutral-950"><div className="text-xs font-medium text-neutral-500">{ar?'انسخه الآن':'Copy now'}</div><div className="mt-2 break-all font-mono text-xs">{raw}</div><button onClick={copy} className="mt-3 inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs"><Copy className="size-3.5"/>{ar?'نسخ':'Copy'}</button></div>}{message&&<p className="mt-3 text-sm text-neutral-500">{message}</p>}</div><div className="rounded-2xl border bg-white dark:border-neutral-800 dark:bg-neutral-900"><div className="border-b p-5"><div className="flex items-center gap-2"><ShieldCheck className="size-4"/><h2 className="font-semibold">{ar?'المفاتيح الحالية':'Current keys'}</h2></div></div><div className="divide-y dark:divide-neutral-800">{keys.map(k=><div key={k.id} className="flex flex-wrap items-center gap-3 p-4"><div className="min-w-40 flex-1"><div className="font-medium">{k.name}</div><div className="mt-1 font-mono text-xs text-neutral-500">{k.key_prefix}… · read</div><div className="mt-1 text-[11px] text-neutral-400">Created {k.created_at}</div></div><div className="text-xs text-neutral-500">{k.last_used_at?('Used '+k.last_used_at):'Never used'}</div><span className="rounded-full border px-2.5 py-1 text-xs">{k.revoked_at?'revoked':'active'}</span>{!k.revoked_at&&<button onClick={()=>revoke(k.id)} className="rounded-lg border p-2 text-red-600"><RotateCcw className="size-4"/></button>}</div>)}{keys.length===0&&<div className="p-10 text-center text-sm text-neutral-500">{ar?'لم تنشئ أي مفاتيح.':'No API keys yet.'}</div>}</div></div></section>
}
