'use client';
import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,CheckSquare,Clock,Plus} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,EmptyState,PageHeader,StatusPill} from '@/components/ui/primitives';

export default function Calendar({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId}=useOrg();const [activities,setActivities]=useState<any[]>([]);const [tasks,setTasks]=useState<any[]>([]);
 const load=async()=>{if(!activeOrgId)return;const from=new Date().toISOString();const to=new Date(Date.now()+14*86400000).toISOString();const [a,t]=await Promise.all([s.from('activities').select('*').eq('org_id',activeOrgId).gte('scheduled_at',from).lte('scheduled_at',to).order('scheduled_at'),s.from('tasks').select('*').eq('org_id',activeOrgId).neq('status','done').gte('due_at',from).lte('due_at',to).order('due_at')]);setActivities(a.data||[]);setTasks(t.data||[])};
 useEffect(()=>{load()},[activeOrgId,s]);
 const total=activities.length+tasks.length;return <section className="space-y-6 p-4 md:p-7"><PageHeader eyebrow={ar?'التخطيط':'Planning'} title={ar?'التقويم وسير العمل':'Calendar & work queue'} description={ar?'كل الزيارات والمتابعات والمهام القادمة في نافذة أسبوعين.':'All upcoming visits, follow-ups, and tasks across the next two weeks.'} actions={<a href={'/'+locale+'/activities'} className="rounded-xl bg-neutral-950 px-3 py-2.5 text-sm text-white dark:bg-white dark:text-neutral-950"><Plus className="me-2 inline size-4"/>{ar?'نشاط جديد':'New activity'}</a>}/><div className="grid gap-3 md:grid-cols-3"><Card className="p-5"><CalendarDays className="size-5 text-neutral-500"/><div className="mt-4 text-xs text-neutral-500">{ar?'بنود التقويم':'Calendar items'}</div><div className="mt-1 text-2xl font-semibold">{total}</div></Card><Card className="p-5"><Clock className="size-5 text-neutral-500"/><div className="mt-4 text-xs text-neutral-500">{ar?'أنشطة مجدولة':'Scheduled activities'}</div><div className="mt-1 text-2xl font-semibold">{activities.length}</div></Card><Card className="p-5"><CheckSquare className="size-5 text-neutral-500"/><div className="mt-4 text-xs text-neutral-500">{ar?'مهام مستحقة':'Tasks due'}</div><div className="mt-1 text-2xl font-semibold">{tasks.length}</div></Card></div><Card className="overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">{ar?'الـ14 يوماً القادمة':'Next 14 days'}</h2></div><div className="divide-y dark:divide-neutral-800">{[...activities.map(x=>({...x,kind:'activity',when:x.scheduled_at})),...tasks.map(x=>({...x,kind:'task',when:x.due_at}))].sort((a,b)=>new Date(a.when||0).getTime()-new Date(b.when||0).getTime()).map(x=><div key={x.kind+'-'+x.id} className="flex items-center gap-3 p-4"><div className="rounded-xl border p-2">{x.kind==='task'?<CheckSquare className="size-4"/>:<CalendarDays className="size-4"/>}</div><div className="min-w-0 flex-1"><div className="font-medium">{x.subject||x.title}</div><div className="mt-1 text-xs text-neutral-500">{new Date(x.when).toLocaleString(locale)}</div></div><StatusPill status={x.status||x.type||'scheduled'}/></div>)}{total===0&&<EmptyState title={ar?'لا توجد عناصر قادمة':'Nothing scheduled'} description={ar?'أضف نشاطاً أو مهمة لتبدأ قائمة العمل.':'Add an activity or task to build the work queue.'}/>}</div></Card></section>;
}
