'use client';
import {useMemo,useState} from 'react';
import {Blocks,Eye,Save,ShieldCheck} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,PageHeader} from '@/components/ui/primitives';
const starters=[['theme','Theme',{kind:'theme',slot:'app-shell',style:'ocean'}],['metric','Metric card',{kind:'metric',slot:'dashboard',source:'v_monthly_trend',metric:'sales'}],['shortcut','Quick shortcut',{kind:'shortcut',slot:'quick-add',label:'My shortcut',href:'/reports'}],['automation','Automation',{kind:'automation',trigger:'invoice.overdue',actions:[{type:'notify'}]}]] as const;
export function ExtensionBuilder({locale}:{locale:'ar'|'en'}){const ar=locale==='ar';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId,role}=useOrg();const can=['owner_admin','sales_manager'].includes(role??'');const [v,setV]=useState({name:'',version:'1.0.0',manifest:'{}'});const [msg,setMsg]=useState('');
 const starter=(m:string,j:any)=>setV(x=>({...x,name:m,manifest:JSON.stringify(j,null,2)}));
 const save=async()=>{if(!activeOrgId||!can||!v.name.trim())return;try{const manifest=JSON.parse(v.manifest);const extension_id=v.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'extension';const {error}=await s.from('extensions').upsert({org_id:activeOrgId,extension_id,version:v.version||'1.0.0',name:v.name,manifest,enabled:true},{onConflict:'org_id,extension_id'});setMsg(error?.message||(ar?'تم حفظ الامتداد.':'Extension saved.'))}catch(e){setMsg(e instanceof Error?e.message:'Invalid JSON')}};
 return <section className="space-y-6 p-4 md:p-7"><PageHeader eyebrow={ar?'المنصة':'Platform'} title={ar?'منشئ الامتدادات':'Extension builder'} description={ar?'ثيمات واختصارات وبطاقات مؤشرات وأتمتة عبر manifest آمن.':'Controlled themes, shortcuts, metric cards, and automation via safe manifests.'}/><div className="grid gap-4 xl:grid-cols-[.75fr_1.25fr]"><Card className="p-5"><div className="flex items-center gap-2 font-semibold"><Blocks className="size-5"/>{ar?'قوالب البداية':'Starters'}</div><div className="mt-4 space-y-2">{starters.map(([id,label,manifest])=><button key={id} onClick={()=>starter(label,manifest)} className="w-full rounded-xl border p-3 text-start hover:bg-neutral-50 dark:hover:bg-neutral-950">{label}</button>)}</div><div className="mt-5 flex gap-2 rounded-xl border p-3 text-xs text-neutral-500"><ShieldCheck className="size-4 shrink-0"/>{ar?'لا يتم تشغيل JavaScript عشوائي من الإضافة.':'Arbitrary JavaScript is not executed by extensions.'}</div></Card><Card className="p-5"><input value={v.name} onChange={e=>setV({...v,name:e.target.value})} placeholder={ar?'اسم الامتداد':'Extension name'} className="w-full rounded-xl border px-3 py-2.5"/><input value={v.version} onChange={e=>setV({...v,version:e.target.value})} placeholder="Version" className="mt-3 w-full rounded-xl border px-3 py-2.5"/><textarea value={v.manifest} onChange={e=>setV({...v,manifest:e.target.value})} className="mt-3 min-h-80 w-full rounded-xl border p-3 font-mono text-xs"/><div className="mt-3 flex gap-2"><button disabled={!can} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm text-white disabled:opacity-40 dark:bg-white dark:text-neutral-950"><Save className="size-4"/>Save</button><button onClick={()=>setV(x=>({...x,manifest:JSON.stringify(JSON.parse(x.manifest),null,2)}))} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm"><Eye className="size-4"/>Format</button></div>{msg&&<p className="mt-3 text-sm text-neutral-500">{msg}</p>}</Card></div></section>
}