'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {Blocks,Code2,Link2,Palette,Play,Plus,Settings2,Webhook} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,EmptyState,MetricCard,PageHeader,StatusPill} from '@/components/ui/primitives';

type Kind='auto'|'webhook'|'extension';

export default function ExtensionsDashboard({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const supabase=useMemo(()=>createClient() as any,[]);const {activeOrgId}=useOrg();
 const [extensions,setExtensions]=useState<any[]>([]);const [autos,setAutos]=useState<any[]>([]);const [webhooks,setWebhooks]=useState<any[]>([]);const [fieldCount,setFieldCount]=useState(0);
 const [open,setOpen]=useState<Kind|null>(null);const [name,setName]=useState('');const [trigger,setTrigger]=useState('deal.created');const [url,setUrl]=useState('');const [events,setEvents]=useState('');
 const load=async()=>{if(!activeOrgId)return;const [e,a,w,f]=await Promise.all([
  supabase.from('extensions').select('*').eq('org_id',activeOrgId).order('created_at',{ascending:false}),
  supabase.from('automations').select('*').eq('org_id',activeOrgId).order('created_at',{ascending:false}),
  supabase.from('webhooks').select('id,org_id,name,url,events,enabled,created_at').eq('org_id',activeOrgId).order('created_at',{ascending:false}),
  supabase.from('custom_fields').select('id',{count:'exact',head:true}).eq('org_id',activeOrgId)
 ]);setExtensions(e.data||[]);setAutos(a.data||[]);setWebhooks(w.data||[]);setFieldCount(f.count||0)};
 useEffect(()=>{load()},[activeOrgId,supabase]);
 const reset=()=>{setName('');setTrigger('deal.created');setUrl('');setEvents('');setOpen(null)};
 const add=async()=>{if(!activeOrgId||!name.trim())return;
  if(open==='auto')await supabase.from('automations').insert({org_id:activeOrgId,name:name.trim(),enabled:true,trigger_key:trigger,conditions:{},actions:[]});
  else if(open==='webhook'&&url.trim())await supabase.from('webhooks').insert({org_id:activeOrgId,name:name.trim(),url:url.trim(),events:events.split(',').map(x=>x.trim()).filter(Boolean),enabled:true});
  else if(open==='extension')await supabase.from('extensions').insert({org_id:activeOrgId,extension_id:(name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'extension')+'-'+Date.now().toString(36),version:'1.0.0',name:name.trim(),manifest:{kind:'shortcut'},enabled:true});
  reset();load();
 };
 const toggle=async(table:'automations'|'webhooks'|'extensions',row:any)=>{if(!activeOrgId)return;await supabase.from(table).update({enabled:!row.enabled}).eq('id',row.id).eq('org_id',activeOrgId);load()};
 return <section className="space-y-6 p-4 md:p-7">
  <PageHeader eyebrow={ar?'المنصة':'Platform'} title={ar?'الامتدادات والتكاملات':'Extensions & integrations'} description={ar?'الأتمتة والويب هوكس والامتدادات والثيمات في طبقة توسعة واحدة.':'Automation, webhooks, extensions, and themes in one expansion layer.'}
   actions={<div className="flex flex-wrap gap-2"><Link href={'/'+locale+'/extensions/builder'} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2.5 text-sm"><Blocks className="size-4"/>{ar?'منشئ الامتدادات':'Extension builder'}</Link><Link href={'/'+locale+'/themes'} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2.5 text-sm"><Palette className="size-4"/>{ar?'الثيمات':'Themes'}</Link></div>}/>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label={ar?'الامتدادات':'Extensions'} value={extensions.length} icon={<Code2 className="size-4"/>}/><MetricCard label={ar?'الأتمتة':'Automations'} value={autos.length} icon={<Play className="size-4"/>}/><MetricCard label={ar?'الويب هوكس':'Webhooks'} value={webhooks.length} icon={<Webhook className="size-4"/>}/><MetricCard label={ar?'الحقول المخصصة':'Custom fields'} value={fieldCount} icon={<Settings2 className="size-4"/>}/></div>
  <div className="grid gap-5 lg:grid-cols-3">
   <Card><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">{ar?'الأتمتة':'Automations'}</h2><p className="mt-1 text-xs text-neutral-500">{ar?'قواعد تعمل بناءً على حدث.':'Event-triggered rules.'}</p></div><button onClick={()=>setOpen('auto')} className="rounded-lg border p-2"><Plus className="size-4"/></button></div><div className="divide-y dark:divide-neutral-800">{autos.map(x=><div key={x.id} className="flex items-center justify-between gap-3 p-4"><div><div className="text-sm font-medium">{x.name}</div><div className="mt-1 text-xs text-neutral-500">{x.trigger_key}</div></div><button onClick={()=>toggle('automations',x)}><StatusPill status={x.enabled?'active':'inactive'}/></button></div>)}{autos.length===0&&<EmptyState title={ar?'لا توجد أتمتة':'No automations'} description={ar?'أضف قاعدة تلقائية.':'Add an automation rule.'}/>}</div></Card>
   <Card><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">{ar?'الويب هوكس':'Webhooks'}</h2><p className="mt-1 text-xs text-neutral-500">{ar?'إشعارات الأنظمة الخارجية.':'Outbound integration events.'}</p></div><button onClick={()=>setOpen('webhook')} className="rounded-lg border p-2"><Plus className="size-4"/></button></div><div className="divide-y dark:divide-neutral-800">{webhooks.map(x=><div key={x.id} className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><div className="text-sm font-medium">{x.name}</div><div className="mt-1 truncate text-xs text-neutral-500">{x.url}</div></div><button onClick={()=>toggle('webhooks',x)}><StatusPill status={x.enabled?'active':'inactive'}/></button></div>)}{webhooks.length===0&&<EmptyState title={ar?'لا توجد Webhooks':'No webhooks'} description={ar?'أضف endpoint للإشعارات.':'Add an endpoint for outbound events.'}/>}</div></Card>
   <Card><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">{ar?'الامتدادات':'Extensions'}</h2><p className="mt-1 text-xs text-neutral-500">{ar?'إضافات منظمة داخل مساحة العمل.':'Installable workspace extensions.'}</p></div><button onClick={()=>setOpen('extension')} className="rounded-lg border p-2"><Plus className="size-4"/></button></div><div className="divide-y dark:divide-neutral-800">{extensions.map(x=><div key={x.id} className="flex items-center justify-between gap-3 p-4"><div><div className="text-sm font-medium">{x.name}</div><div className="mt-1 text-xs text-neutral-500">{x.extension_id} · v{x.version}</div></div><button onClick={()=>toggle('extensions',x)}><StatusPill status={x.enabled?'active':'inactive'}/></button></div>)}{extensions.length===0&&<EmptyState title={ar?'لا توجد امتدادات':'No extensions'} description={ar?'استخدم منشئ الامتدادات لإنشاء ثيمات وأدوات.':'Use the builder to create themes and tools.'}/>}</div></Card>
  </div>
  <div className="grid gap-4 md:grid-cols-3"><Link href={'/'+locale+'/extensions/api-keys'} className="rounded-2xl border p-5 hover:bg-neutral-50 dark:border-neutral-800"><Link2 className="size-5"/><div className="mt-3 font-semibold">API keys</div></Link><Link href={'/'+locale+'/extensions/webhooks'} className="rounded-2xl border p-5 hover:bg-neutral-50 dark:border-neutral-800"><Webhook className="size-5"/><div className="mt-3 font-semibold">Webhooks</div></Link><Link href={'/'+locale+'/extensions/automations'} className="rounded-2xl border p-5 hover:bg-neutral-50 dark:border-neutral-800"><Play className="size-5"/><div className="mt-3 font-semibold">{ar?'أتمتة':'Automation'}</div></Link></div>
  {open&&<div className="fixed inset-0 z-[80] bg-black/40 p-4 backdrop-blur-sm"><Card className="mx-auto mt-[18vh] max-w-lg p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-semibold">{open==='auto'?(ar?'إضافة أتمتة':'Add automation'):open==='webhook'?(ar?'إضافة Webhook':'Add webhook'):(ar?'إضافة امتداد':'Add extension')}</h2><button onClick={reset} className="text-sm text-neutral-500">Esc</button></div><div className="mt-4 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder={ar?'الاسم':'Name'} className="w-full rounded-xl border px-3 py-2.5"/>{open==='auto'&&<select value={trigger} onChange={e=>setTrigger(e.target.value)} className="w-full rounded-xl border bg-transparent px-3 py-2.5"><option>deal.created</option><option>deal.stage_changed</option><option>invoice.overdue</option><option>payment.received</option><option>activity.completed</option><option>customer.inactive</option></select>}{open==='webhook'&&<><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/webhook" className="w-full rounded-xl border px-3 py-2.5"/><input value={events} onChange={e=>setEvents(e.target.value)} placeholder="deal.created,invoice.created" className="w-full rounded-xl border px-3 py-2.5"/></>}<button onClick={add} className="w-full rounded-xl bg-neutral-950 px-4 py-2.5 text-sm text-white dark:bg-white dark:text-neutral-950">{ar?'حفظ':'Save'}</button></div></Card></div>}
 </section>;
}
