'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {BookOpen,ChevronDown,LoaderCircle,Send,Sparkles,Smile} from 'lucide-react';

const suggestions={ar:['ماذا يحتاج انتباهي اليوم؟','حلل المبيعات والـPipeline','من المتأخر في السداد؟','كيف أحسب رواتب الفريق؟'],en:['What needs my attention today?','Analyze sales and pipeline','Who is overdue?','How do I calculate payroll?']};

type Mood='idle'|'thinking'|'happy'|'curious'|'confused';
function Stone({mood}:{mood:Mood}){
 const face=mood==='happy'?'happy':mood==='thinking'?'thinking':mood==='curious'?'curious':mood==='confused'?'confused':'idle';
 return <span className={'solid-stone solid-stone-'+face} aria-hidden="true"><span className="solid-arm solid-arm-left"/><span className="solid-arm solid-arm-right"/><span className="solid-eye solid-eye-left"/><span className="solid-eye solid-eye-right"/><span className="solid-mouth"/><span className="solid-foot solid-foot-left"/><span className="solid-foot solid-foot-right"/></span>
}

export function SolidAiDock({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const [open,setOpen]=useState(false);const [q,setQ]=useState('');const [answer,setAnswer]=useState<any>(null);const [busy,setBusy]=useState(false);const [configured,setConfigured]=useState(false);const [mood,setMood]=useState<Mood>('idle');const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{fetch('/api/ai/status',{cache:'no-store'}).then(r=>r.json()).then(d=>setConfigured(Boolean(d.configured))).catch(()=>{});const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='s'){e.preventDefault();setOpen(v=>!v)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 useEffect(()=>{if(open){setMood('curious');window.setTimeout(()=>input.current?.focus(),60)}},[open]);
 useEffect(()=>{if(mood==='idle')return;const id=window.setTimeout(()=>setMood('idle'),2400);return()=>window.clearTimeout(id)},[mood]);
 const ask=async(text=q)=>{const question=text.trim();if(!question||busy)return;setBusy(true);setMood('thinking');setAnswer(null);try{const r=await fetch('/api/assistant',{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({question,locale})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI request failed');setAnswer(d);setMood('happy');setQ('')}catch(error){setAnswer({mode:'error',error:error instanceof Error?error.message:'AI request failed'});setMood('confused')}finally{setBusy(false)}};
 return <div className="solid-ai-rail" dir={ar?'rtl':'ltr'}><button type="button" className="solid-ai-main" onClick={()=>setOpen(v=>!v)} aria-label={ar?'فتح SOLID':'Open SOLID'}><span className="solid-stone-wrap"><Stone mood={mood}/></span><span className="min-w-0 text-start"><strong className="block text-[12px] tracking-tight">SOLID</strong><span className="block text-[10px] text-neutral-400">{configured?(ar?'متصل بـ Gemini':'Gemini connected'):(ar?'اسألني أي شيء':'Ask me anything')}</span></span><span className={"solid-ai-dot "+(configured?'is-live':'')}/><ChevronDown className={'size-3.5 text-neutral-400 transition '+(open?'rotate-180':'')}/></button>{open&&<div className="solid-ai-popover"><div className="border-b p-4 dark:border-neutral-800"><div className="flex items-center gap-2"><Stone mood={mood}/><div><div className="font-semibold">SOLID</div><div className="text-[11px] text-neutral-500">{configured?(ar?'يعمل الآن مع Gemini':'Powered by Gemini'):(ar?'وضع محلي مجاني':'Free local mode')}</div></div><Link href={'/'+locale+'/help'} className="ms-auto rounded-xl border p-2" aria-label={ar?'دليل':'Guide'}><BookOpen className="size-4"/></Link></div></div><div className="flex flex-wrap gap-2 p-3">{suggestions[locale].map(item=><button key={item} onClick={()=>{setQ(item);void ask(item)}} className="rounded-full border px-3 py-2 text-xs hover:bg-neutral-100 dark:hover:bg-neutral-800"><Sparkles className="me-1 inline size-3"/>{item}</button>)}</div><form onSubmit={e=>{e.preventDefault();void ask()}} className="border-t p-3 dark:border-neutral-800"><div className="flex gap-2"><input ref={input} value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'اسأل SOLID...':'Ask SOLID...'} className="min-w-0 flex-1 rounded-xl border bg-neutral-50 px-3 py-3 text-sm outline-none dark:border-neutral-800 dark:bg-neutral-900"/><button disabled={busy} className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-neutral-950 text-white disabled:opacity-50 dark:bg-white dark:text-neutral-950">{busy?<LoaderCircle className="size-4 animate-spin"/>:<Send className="size-4"/>}</button></div></form>{answer&&<div className="border-t p-4 dark:border-neutral-800"><div className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-neutral-400"><Smile className="size-3"/>{answer.mode==='real'?(ar?'Gemini AI حقيقي':'Real Gemini AI'):answer.mode==='local'?(ar?'الوضع المحلي':'Local mode'):'AI error'}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{answer.text||answer.error}</p></div>}</div>}</div>
}