'use client';
import {useState} from 'react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';

export default function ImportPage(){
 const p=typeof window!=='undefined'?window.location.pathname:'/ar/import';const locale=p.split('/')[1]||'ar';const ar=locale!=='en';const s=createClient();const {activeOrgId}=useOrg();
 const [entity,setEntity]=useState('accounts');const [preview,setPreview]=useState<string[][]>([]);const [status,setStatus]=useState('');
 const parse=async(file:File)=>{try{const ext=file.name.toLowerCase();let rows:string[][]=[];if(ext.endsWith('.xlsx')||ext.endsWith('.xls')){const XLSX=await import('xlsx');const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json<string[]>(ws,{header:1,raw:false}) as string[][]}else{const txt=await file.text();rows=txt.split(/\r?\n/).filter(Boolean).map(r=>r.split(','))}setPreview(rows.slice(0,101));setStatus('preview')}catch(e){setStatus(e instanceof Error?e.message:'Unable to parse file')}};
 const commit=async()=>{if(!activeOrgId||preview.length<2)return;const headers=preview[0].map(x=>x.trim().toLowerCase());const rows=preview.slice(1);if(entity==='accounts'){const payload=rows.map(r=>({org_id:activeOrgId,name:r[headers.indexOf('name')]||r[headers.indexOf('customer')]||'',phone:r[headers.indexOf('phone')]||'',email:r[headers.indexOf('email')]||'',industry:r[headers.indexOf('industry')]||''})).filter(x=>x.name);const {error}=await s.from('accounts').insert(payload);setStatus(error?error.message:(ar?'تم استيراد '+payload.length+' سجل.':'Imported '+payload.length+' records.'))}else setStatus(ar?'المعاينة تدعم كل الجداول، والاعتماد المباشر متاح للحسابات حالياً.':'Preview supports all spreadsheets; direct commit is currently enabled for Accounts.')};
 return <section className="p-4 md:p-8"><h1 className="text-2xl font-semibold">{ar?'استيراد البيانات':'Import data'}</h1><p className="mt-1 text-sm text-neutral-500">{ar?'استيراد CSV أو Excel مع معاينة قبل الحفظ.':'Import CSV or Excel with a preview before commit.'}</p><div className="mt-5 rounded-2xl border bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex flex-wrap gap-3"><select value={entity} onChange={e=>setEntity(e.target.value)} className="rounded-xl border bg-transparent px-3 py-2"><option value="accounts">{ar?'الحسابات':'Accounts'}</option><option value="contacts">{ar?'جهات الاتصال':'Contacts'}</option><option value="products">{ar?'المنتجات':'Products'}</option><option value="invoices">{ar?'الفواتير':'Invoices'}</option></select><input type="file" accept=".csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>e.target.files?.[0]&&parse(e.target.files[0])} className="text-sm"/></div>{preview.length>0&&<><div className="mt-5 overflow-x-auto"><table className="min-w-full text-xs"><tbody>{preview.slice(0,8).map((r,i)=><tr key={i} className="border-b dark:border-neutral-800">{r.map((c,j)=><td key={j} className="px-3 py-2 whitespace-nowrap">{c}</td>)}</tr>)}</tbody></table></div><button onClick={commit} className="mt-4 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm text-white dark:bg-white dark:text-neutral-950">{ar?'اعتماد الاستيراد':'Commit import'}</button></>}{status&&<p className="mt-3 text-sm text-neutral-500">{status}</p>}</div></section>
}
