'use client';

import {useEffect,useMemo,useState} from 'react';
import {useParams,usePathname} from 'next/navigation';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';

export default function InvoiceDetail(){
 const {id}=useParams<{id:string}>();const path=usePathname();const locale=path.split('/')[1]||'ar';const ar=locale!=='en';
 const s=useMemo(()=>createClient(),[]);const {activeOrgId}=useOrg();
 const [invoice,setInvoice]=useState<any>(null);const [lines,setLines]=useState<any[]>([]);const [amount,setAmount]=useState('');const [method,setMethod]=useState('cash');const [message,setMessage]=useState('');
 const load=async()=>{if(!activeOrgId||!id)return;const [{data:i},{data:l}]=await Promise.all([s.from('invoices').select('*').eq('id',id).eq('org_id',activeOrgId).single(),s.from('invoice_lines').select('*,products(name)').eq('invoice_id',id).eq('org_id',activeOrgId)]);setInvoice(i);setLines(l??[])};
 useEffect(()=>{load()},[activeOrgId,id,s]);
 const pay=async()=>{setMessage('');const n=Number(amount);if(!n||!invoice)return;const {error}=await s.rpc('record_payment_and_allocate',{p_invoice_id:invoice.id,p_amount:n,p_method:method,p_reference:null});if(error)setMessage(error.message);else{setAmount('');setMessage(ar?'تم تسجيل التحصيل.':'Payment recorded.');await load()}};
 if(!invoice)return <section className="p-8 text-neutral-500">{ar?'جاري التحميل...':'Loading...'}</section>;
 return <section className="p-4 md:p-8"><div className="rounded-3xl border bg-white p-6 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-neutral-500">{ar?'فاتورة':'Invoice'}</p><h1 className="mt-1 text-3xl font-semibold">{invoice.invoice_number}</h1><p className="mt-1 text-sm text-neutral-500">{invoice.issue_date} · {invoice.status}</p></div><div className="text-end"><div className="text-xs text-neutral-500">{ar?'الإجمالي':'Total'}</div><div className="text-3xl font-semibold">{Number(invoice.total).toLocaleString()} {invoice.currency}</div><div className="text-sm text-neutral-500">{ar?'المتبقي':'Balance'} {Number(invoice.balance_due).toLocaleString()} {invoice.currency}</div></div></div>
 <div className="mt-6 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b dark:border-neutral-800"><th className="px-3 py-2 text-start">{ar?'المنتج':'Product'}</th><th className="px-3 py-2 text-start">{ar?'الكمية':'Qty'}</th><th className="px-3 py-2 text-start">{ar?'السعر':'Price'}</th><th className="px-3 py-2 text-start">{ar?'الإجمالي':'Net'}</th><th className="px-3 py-2 text-start">{ar?'الربح':'GP'}</th></tr></thead><tbody>{lines.map(l=><tr key={l.id} className="border-b last:border-0 dark:border-neutral-800"><td className="px-3 py-2">{l.products?.name||l.product_id}</td><td className="px-3 py-2">{l.qty}</td><td className="px-3 py-2">{Number(l.unit_price).toLocaleString()}</td><td className="px-3 py-2">{Number(l.net_sales).toLocaleString()}</td><td className="px-3 py-2">{Number(l.gross_profit).toLocaleString()}</td></tr>)}</tbody></table></div>
 <div className="mt-6 max-w-xl rounded-2xl border p-4 dark:border-neutral-800"><h2 className="font-semibold">{ar?'تسجيل تحصيل':'Record collection'}</h2><div className="mt-3 flex gap-2"><input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={ar?'المبلغ':'Amount'} className="min-w-0 flex-1 rounded-xl border px-3 py-2.5"/><select value={method} onChange={e=>setMethod(e.target.value)} className="rounded-xl border bg-transparent px-3 py-2.5"><option value="cash">Cash</option><option value="bank">Bank</option><option value="card">Card</option><option value="transfer">Transfer</option><option value="other">Other</option></select><button onClick={pay} className="rounded-xl bg-neutral-950 px-4 py-2.5 text-white dark:bg-white dark:text-neutral-950">{ar?'تحصيل':'Collect'}</button></div>{message&&<p className="mt-3 text-sm text-neutral-500">{message}</p>}</div>
 </div></section>
}
