'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,Plus,Receipt} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,EmptyState,PageHeader,StatusPill} from '@/components/ui/primitives';
const fallback=[{id:'p1',name:'Prospecting',probability:10},{id:'p2',name:'Qualification',probability:30},{id:'p3',name:'Proposal',probability:60},{id:'p4',name:'Negotiation',probability:80},{id:'p5',name:'Won',probability:100},{id:'p6',name:'Lost',probability:0}];
export default function Pipeline(){const p=typeof window!=='undefined'?window.location.pathname:'/ar/pipeline';const locale=(p.split('/')[1]||'ar') as 'ar'|'en';const ar=locale==='ar';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId}=useOrg();const [stages,setStages]=useState<any[]>([]);const [deals,setDeals]=useState<any[]>([]);const [quotes,setQuotes]=useState<any[]>([]);const load=async()=>{if(!activeOrgId)return;const [{data:st},{data:d},{data:q}]=await Promise.all([s.from('pipeline_stages').select('*').eq('org_id',activeOrgId).order('stage_order'),s.from('deals').select('*').eq('org_id',activeOrgId).order('value',{ascending:false}),s.from('quotes').select('*').eq('org_id',activeOrgId).order('created_at',{ascending:false})]);setStages(st?.length?st:fallback);setDeals(d||[]);setQuotes(q||[])};useEffect(()=>{load()},[activeOrgId]);
const move=async(id:string,stageId:string)=>{if(!activeOrgId)return;await s.from('deals').update({stage_id:stageId,status:['Won','Lost'].includes(String(stages.find(x=>x.id===stageId)?.name))?'closed':'open'}).eq('id',id).eq('org_id',activeOrgId);load()};
const convert=async(q:any)=>{if(!activeOrgId)return;const {data:invoice,error}=await s.from('invoices').insert({org_id:activeOrgId,account_id:q.customer_id,issue_date:new Date().toISOString().slice(0,10),status:'draft',currency:'EGP',total:Number(q.value||0),subtotal:Number(q.value||0),balance_due:Number(q.value||0)}).select('id').single();if(error||!invoice)return;const {data:lines}=await s.from('quote_lines').select('*').eq('quote_id',q.id).eq('org_id',activeOrgId);if(lines?.length)await s.from('invoice_lines').insert(lines.map((l:any)=>({org_id:activeOrgId,invoice_id:invoice.id,product_id:l.product_id,qty:l.qty,unit_price:l.unit_price,discount:l.discount,cost_total:0})));await s.from('quotes').update({stage:'won',converted_invoice_id:invoice.id}).eq('id',q.id).eq('org_id',activeOrgId);await load()};
return <section className="space-y-6 p-4 md:p-7"><PageHeader eyebrow={ar?'الفرص والعروض':'Pipeline & quotes'} title={ar?'خط المبيعات':'Pipeline'} description={ar?'لوحة الفرص + عروض الأسعار مع تحويل مباشر للبيع.':'Opportunity board plus quotes with one-click conversion to an invoice.'} actions={<Link href={'/'+locale+'/pipeline/new'} className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-3 py-2.5 text-sm text-white dark:bg-white dark:text-neutral-950"><Plus className="size-4"/>{ar?'عرض سعر جديد':'New quote'}</Link>}/><div className="grid gap-3 overflow-x-auto xl:grid-cols-6">{stages.map(st=>{const cards=deals.filter(d=>d.stage_id===st.id);return <Card key={st.id} className="min-w-64 p-3"><div className="flex items-center justify-between"><div><div className="font-semibold">{st.name}</div><div className="text-xs text-neutral-500">{cards.length} · {cards.reduce((n,d)=>n+Number(d.value||0),0).toLocaleString()} EGP</div></div><span className="text-xs text-neutral-500">{st.probability}%</span></div><div className="mt-3 space-y-2">{cards.map(d=><div key={d.id} className="rounded-xl border p-3 dark:border-neutral-800"><div className="text-sm font-medium">{d.title}</div><div className="mt-1 text-sm">{Number(d.value||0).toLocaleString()} EGP</div><div className="mt-2 flex gap-1 overflow-x-auto">{stages.filter(x=>x.id!==st.id).slice(0,3).map(x=><button key={x.id} onClick={()=>move(d.id,x.id)} className="shrink-0 rounded-lg border px-2 py-1 text-[11px]"><ArrowRight className="inline size-3"/>{x.name}</button>)}</div></div>)}</div></Card>})}</div><Card><div className="border-b p-5 dark:border-neutral-800"><h2 className="font-semibold">{ar?'عروض تحتاج إجراء':'Quotes requiring action'}</h2></div><div className="divide-y dark:divide-neutral-800">{quotes.filter(q=>!q.converted_invoice_id).slice(0,10).map(q=><div key={q.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><div className="font-medium">{q.quote_number}</div><div className="mt-1 text-xs text-neutral-500">{q.stage} · {q.follow_up_date||'—'} · {Number(q.value||0).toLocaleString()} EGP</div></div><div className="flex gap-2"><StatusPill status={q.stage}/>{q.stage!=='won'&&<button onClick={()=>convert(q)} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-xs"><Receipt className="size-3"/>{ar?'تحويل لفاتورة':'Convert to invoice'}</button>}</div></div>)}{quotes.filter(q=>!q.converted_invoice_id).length===0&&<EmptyState title={ar?'لا توجد عروض مفتوحة':'No open quotes'} description={ar?'أنشئ عرض سعر لبدء المتابعة.':'Create a quote to start follow-up.'}/>}</div></Card></section>}
