'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Activity,ArrowUpRight,BriefcaseBusiness,Building2,CalendarClock,CheckSquare,Coins,Receipt,Sparkles,Target,Users,WalletCards,AlertTriangle} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {SalesChart} from '@/components/dashboard/sales-chart';
import {Card,EmptyState,MetricCard,PageHeader,StatusPill} from '@/components/ui/primitives';

const money=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n)+' EGP';

export function Dashboard({locale}:{locale:'ar'|'en'}){
 const ar=locale==='ar';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId,role}=useOrg();
 const privileged=['owner_admin','sales_manager','supervisor','accountant_hr'].includes(role??'');
 const [stats,setStats]=useState({sales:0,target:0,collection:0,pipeline:0,accounts:0,leads:0,tasks:0,quotes:0,gp:0,gpPct:0});const [attention,setAttention]=useState<any[]>([]);const [deals,setDeals]=useState<any[]>([]);const [activities,setActivities]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{let dead=false;(async()=>{if(!activeOrgId){setLoading(false);return}setLoading(true);const d=new Date();d.setDate(1);const month=d.toISOString().slice(0,10);const today=new Date().toISOString().slice(0,10);
 const [inv,tgt,acc,lead,deal,task,pay,quote,alert,act]=await Promise.all([
  s.from('invoices').select('total').eq('org_id',activeOrgId).gte('issue_date',month).neq('status','void'),
  s.from('targets').select('value').eq('org_id',activeOrgId).eq('metric','sales').eq('scope','company').limit(1),
  s.from('accounts').select('*',{count:'exact',head:true}).eq('org_id',activeOrgId),
  s.from('leads').select('*',{count:'exact',head:true}).eq('org_id',activeOrgId),
  s.from('deals').select('id,title,value,expected_close_date').eq('org_id',activeOrgId).eq('status','open').order('value',{ascending:false}).limit(6),
  s.from('tasks').select('id,title,priority,due_at').eq('org_id',activeOrgId).neq('status','done').order('due_at').limit(6),
  s.from('payments').select('amount').eq('org_id',activeOrgId).eq('status','received').gte('payment_date',month),
  s.from('quotes').select('id,quote_number,follow_up_date').eq('org_id',activeOrgId).lte('follow_up_date',today).not('stage','in','(won,lost)').limit(6),
  s.from('alerts').select('id,title,severity,suggested_action').eq('org_id',activeOrgId).neq('status','resolved').order('created_at',{ascending:false}).limit(6),
  s.from('activities').select('id,type,subject,scheduled_at').eq('org_id',activeOrgId).order('created_at',{ascending:false}).limit(6)
 ]);
 let gp=0,gpSales=0;if(privileged){const z=await s.from('v_monthly_trend').select('period_month,gp,sales').eq('org_id',activeOrgId).order('period_month',{ascending:false}).limit(1);gp=Number(z.data?.[0]?.gp||0);gpSales=Number(z.data?.[0]?.sales||0)}
 if(dead)return;const sales=(inv.data||[]).reduce((n:number,r:any)=>n+Number(r.total||0),0);const target=Number(tgt.data?.[0]?.value||0);const collection=(pay.data||[]).reduce((n:number,r:any)=>n+Number(r.amount||0),0);const pipeline=(deal.data||[]).reduce((n:number,r:any)=>n+Number(r.value||0),0);
 setStats({sales,target,collection,pipeline,accounts:acc.count||0,leads:lead.count||0,tasks:task.data?.length||0,quotes:quote.data?.length||0,gp,gpPct:gpSales?gp/gpSales:0});
 setAttention([...(alert.data||[]).map((x:any)=>({...x,kind:'alert'})),...(quote.data||[]).map((x:any)=>({id:x.id,title:(ar?'عرض سعر ':'Quote ')+(x.quote_number||''),severity:'medium',suggested_action:ar?'متابعة العرض اليوم.':'Follow up today.',kind:'quote'})),...(task.data||[]).map((x:any)=>({...x,kind:'task'}))]);setDeals(deal.data||[]);setActivities(act.data||[]);setLoading(false)
 })();return()=>{dead=true}},[activeOrgId,ar,privileged,s]);
 const achievement=stats.target?stats.sales/stats.target:0;
 return <div><div className="border-b bg-neutral-950 px-4 py-6 text-white md:px-7"><div className="mx-auto max-w-[1400px]"><p className="text-xs uppercase tracking-[0.18em] text-neutral-400">SalesOS · {ar?'اليوم':'Today'}</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold md:text-3xl">{ar?'لوحة قيادة المبيعات والعمليات':'Sales & operations command center'}</h1><p className="mt-1 text-sm text-neutral-400">{ar?'مركز العمل اليومي.':'Your daily operating view.'}</p></div><Link href={'/'+locale+'/brief'} className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-3 py-2 text-xs"><Sparkles className="size-4"/>{ar?'موجز اليوم':'Daily brief'}</Link></div></div></div>
 <section className="mx-auto max-w-[1400px] space-y-6 px-4 py-6 md:px-7"><PageHeader eyebrow={ar?'مركز القيادة':'Command center'} title={ar?'ماذا يحتاج انتباهك؟':'What needs attention?'} description={ar?'المبيعات والتحصيل والعملاء والمهام في شاشة واحدة.':'Sales, collections, customers and tasks in one screen.'} actions={<div className="flex gap-2"><Link href={'/'+locale+'/sales/new'} className="rounded-xl bg-neutral-950 px-3 py-2.5 text-sm text-white dark:bg-white dark:text-neutral-950"><Receipt className="me-2 inline size-4"/>{ar?'بيع سريع':'Quick sale'}</Link><Link href={'/'+locale+'/activities/new'} className="rounded-xl border px-3 py-2.5 text-sm"><Activity className="me-2 inline size-4"/>{ar?'نشاط':'Activity'}</Link></div>}/>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label={ar?'المبيعات الشهرية':'Monthly sales'} value={loading?'—':money(stats.sales)} sub={stats.target?Math.round(achievement*100)+'%':ar?'لا يوجد هدف':'No target'} icon={<Receipt className="size-4"/>}/><MetricCard label={ar?'الهدف':'Target'} value={loading?'—':money(stats.target)} href={'/'+locale+'/targets'} icon={<Target className="size-4"/>}/><MetricCard label={ar?'التحصيل':'Collections'} value={loading?'—':money(stats.collection)} href={'/'+locale+'/collections'} icon={<WalletCards className="size-4"/>}/><MetricCard label={ar?'الـPipeline':'Pipeline'} value={loading?'—':money(stats.pipeline)} href={'/'+locale+'/pipeline'} icon={<BriefcaseBusiness className="size-4"/>}/><MetricCard label={ar?'العملاء':'Customers'} value={loading?'—':stats.accounts} sub={stats.leads+' '+(ar?'عملاء محتملون':'leads')} href={'/'+locale+'/accounts'} icon={<Users className="size-4"/>}/></div>
 <div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><Card className="overflow-hidden"><div className="border-b p-5 dark:border-neutral-800"><div className="flex items-center justify-between"><div><h2 className="font-semibold">{ar?'يحتاج إجراء':'Needs attention'}</h2><p className="mt-1 text-xs text-neutral-500">{ar?'المتابعات الأقرب لخسارة الإيراد أو تأخير العمل.':'Items most likely to lose revenue or delay work.'}</p></div><Link href={'/'+locale+'/alerts'} className="text-xs text-neutral-500">{ar?'التنبيهات':'Alerts'} <ArrowUpRight className="inline size-3"/></Link></div></div>{attention.length?<div className="divide-y dark:divide-neutral-800">{attention.slice(0,8).map((x:any)=><div key={x.id} className="flex items-start gap-3 p-4"><span className="rounded-xl border p-2">{x.kind==='task'?<CheckSquare className="size-4"/>:x.kind==='quote'?<CalendarClock className="size-4"/>:<AlertTriangle className="size-4" />}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="truncate text-sm font-medium">{x.title||x.subject}</span><StatusPill status={x.severity||x.priority||'medium'}/></div><p className="mt-1 text-xs text-neutral-500">{x.suggested_action||''}</p></div></div>)}</div>:<EmptyState title={ar?'كل شيء هادئ':'You are clear'} description={ar?'لا توجد متابعة عاجلة.':'No urgent follow-up.'}/>}</Card>
 <Card><div className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">{ar?'صحة الهدف':'Target health'}</h2><p className="mt-1 text-xs text-neutral-500">{ar?'التقدم مقابل الهدف':'Progress against target'}</p></div><div className="text-2xl font-semibold">{Math.round(achievement*100)}%</div></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-neutral-100 dark:bg-neutral-800"><div className="h-full bg-neutral-950 dark:bg-white" style={{width:Math.min(100,Math.max(0,achievement*100))+'%'}}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl border p-3"><div className="text-xs text-neutral-500">{ar?'المتبقي':'Remaining'}</div><div className="mt-1 font-semibold">{money(Math.max(0,stats.target-stats.sales))}</div></div><div className="rounded-xl border p-3"><div className="text-xs text-neutral-500">{ar?'مهام مفتوحة':'Open tasks'}</div><div className="mt-1 font-semibold">{stats.tasks}</div></div></div></div>{privileged&&<div className="border-t p-5 dark:border-neutral-800"><div className="flex items-center gap-2 text-sm font-medium"><Coins className="size-4"/>{ar?'هامش الربح':'Gross profit'}</div><div className="mt-2 text-2xl font-semibold">{money(stats.gp)}</div><p className="mt-1 text-xs text-neutral-500">{(stats.gpPct*100).toFixed(1)}%</p></div>}</Card></div>
 <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><SalesChart locale={locale}/><Card><div className="border-b p-5 dark:border-neutral-800"><h2 className="font-semibold">{ar?'أكبر الفرص':'Largest opportunities'}</h2></div>{deals.length?<div className="divide-y dark:divide-neutral-800">{deals.map(d=><Link key={d.id} href={'/'+locale+'/deals'} className="flex items-center justify-between gap-3 p-4"><div><p className="text-sm font-medium">{d.title}</p><p className="mt-1 text-xs text-neutral-500">{d.expected_close_date||'—'}</p></div><span className="text-sm font-semibold">{money(Number(d.value||0))}</span></Link>)}</div>:<EmptyState title={ar?'لا توجد فرص':'No opportunities'} description={ar?'أضف فرصة أو عرض سعر.':'Add an opportunity or quote.'}/>}</Card></div>
 <div className="grid gap-5 xl:grid-cols-2"><Card><div className="border-b p-5"><h2 className="font-semibold">{ar?'آخر الأنشطة':'Recent activity'}</h2></div>{activities.length?<div className="divide-y dark:divide-neutral-800">{activities.map(a=><div key={a.id} className="p-4"><div className="text-sm font-medium">{a.subject}</div><div className="mt-1 text-xs text-neutral-500">{a.type} · {a.scheduled_at||'—'}</div></div>)}</div>:<EmptyState title={ar?'لا توجد أنشطة':'No activity yet'} description={ar?'سجّل زيارة أو مكالمة.':'Log a visit or call.'}/>}</Card><Card><div className="border-b p-5"><h2 className="font-semibold">{ar?'اختصارات':'Shortcuts'}</h2></div><div className="grid gap-2 p-4 sm:grid-cols-2"><Link href={'/'+locale+'/accounts'} className="rounded-xl border p-3 text-sm"><Building2 className="me-2 inline size-4"/>{ar?'العملاء':'Customers'}</Link><Link href={'/'+locale+'/collections'} className="rounded-xl border p-3 text-sm"><WalletCards className="me-2 inline size-4"/>{ar?'التحصيل':'Collections'}</Link><Link href={'/'+locale+'/targets'} className="rounded-xl border p-3 text-sm"><Target className="me-2 inline size-4"/>{ar?'الأهداف':'Targets'}</Link><Link href={'/'+locale+'/reports'} className="rounded-xl border p-3 text-sm"><ArrowUpRight className="me-2 inline size-4"/>{ar?'التقارير':'Reports'}</Link></div></Card></div></section></div>;
}