'use client';

import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,Clock3,RefreshCw,RotateCcw} from 'lucide-react';
import {createClient} from '@/lib/supabase/browser';
import {useOrg} from '@/lib/org/context';
import {Card,EmptyState,PageHeader,StatusPill} from '@/components/ui/primitives';

export default function Alerts(){
 const p=typeof window!=='undefined'?window.location.pathname:'/ar/alerts';const ar=p.split('/')[1]!=='en';const s=useMemo(()=>createClient() as any,[]);const {activeOrgId}=useOrg();const [rows,setRows]=useState<any[]>([]);const [busy,setBusy]=useState<string|null>(null);
 const load=async()=>{if(!activeOrgId)return;const {data}=await s.from('alerts').select('*').eq('org_id',activeOrgId).order('created_at',{ascending:false});setRows(data??[])};
 useEffect(()=>{load()},[activeOrgId]);
 const change=async(id:string,status:string,extra:any={})=>{if(!activeOrgId)return;setBusy(id);await s.from('alerts').update({status,...extra}).eq('id',id).eq('org_id',activeOrgId);setBusy(null);load()};
 const snooze=(id:string)=>change(id,'ack',{snoozed_until:new Date(Date.now()+24*60*60*1000).toISOString()});
 return <section className="space-y-6 p-4 md:p-7"><PageHeader eyebrow={ar?'التحكم':'Control'} title={ar?'التنبيهات والمخاطر':'Alerts & risks'} description={ar?'التنبيهات الآلية تحتاج إجراء أو تأكيد أو تأجيل، ولا تختفي بصمت.':'Automated risks need action, acknowledgement, or snooze—they do not disappear silently.'} actions={<button onClick={load} className="rounded-xl border px-3 py-2.5 text-sm"><RefreshCw className="me-2 inline size-4"/>{ar?'تحديث':'Refresh'}</button>}/><div className="space-y-3">{rows.map(r=><Card key={r.id} className="p-4"><div className="flex flex-wrap items-start gap-3"><span className="rounded-xl border p-2"><AlertTriangle className="size-5"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{r.title}</h2><StatusPill status={r.severity}/><StatusPill status={r.status}/></div><p className="mt-2 text-sm text-neutral-500">{r.suggested_action||''}</p><div className="mt-1 text-[11px] text-neutral-400">{new Date(r.created_at).toLocaleString(ar?'ar-EG':'en-US')}{r.snoozed_until?' · '+(ar?'مؤجل حتى ':'Snoozed until ')+new Date(r.snoozed_until).toLocaleString() : ''}</div></div><div className="flex flex-wrap gap-2">{r.status!=='resolved'&&<button disabled={busy===r.id} onClick={()=>change(r.id,'ack')} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><CheckCircle2 className="size-3.5"/>{ar?'تأكيد':'Acknowledge'}</button>}{r.status!=='resolved'&&<button disabled={busy===r.id} onClick={()=>snooze(r.id)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><Clock3 className="size-3.5"/>{ar?'تأجيل 24 ساعة':'Snooze 24h'}</button>}{r.status!=='resolved'&&<button disabled={busy===r.id} onClick={()=>change(r.id,'resolved',{resolved_at:new Date().toISOString()})} className="inline-flex items-center gap-1 rounded-lg bg-neutral-950 px-3 py-2 text-xs text-white dark:bg-white dark:text-neutral-950"><RotateCcw className="size-3.5"/>{ar?'حل':'Resolve'}</button>}</div></div></Card>)}{rows.length===0&&<EmptyState title={ar?'لا توجد تنبيهات':'No alerts'} description={ar?'ستظهر هنا المخاطر المكتشفة آلياً.':'Detected risks will appear here automatically.'}/>}</div></section>
}
